### PR TITLE
[NetManager] enable user and account settings update

### PR DESCRIPTION
**Pull request by ja-odur**
#### Summary of Changes (What does this PR do?)
- Enable authenticated user to update their information

#### Is this change ready to hit production in its current state?
- [ ] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [ ] I consider this code done
- [ ] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

Good to have (up to reviewer's discretion):
- [ ] I've tested this on staging
- [ ] Unit test coverage of changes

#### How should this be manually tested?
* Pull and checkout to this [branch]() locally
* Install node requirements `npm install`
* Ensure the local auth-service with data-segregation is running. Check this [PR](https://github.com/airqo-platform/AirQo-api/pull/121) for more info
* You start the application in one of the two ways:
  1. `npm run dev-mac` (on mac) or `npm run dev-pc` (on windows platform)
  2. `npm run prod-mac` (on mac) or `npm run prod-pc` (on windows platform) and manually change the auth-service url configs to point to the locally running service. The benefit of this approach is you are able to load other data required by the app (such as analytics).
* On Accounts and Settings page, you should be able to edit user details and passwords respectively
#### What are the relevant tickets?
- [PLAT-119](https://airqoteam.atlassian.net/browse/PLAT-119)

#### Screenshots (optional)

### CODE REVIEW

**Review by Baalmart — COMMENTED** [review]
Awesome work @ja-odur , looks like things are taking shape. :) 

Just some few observations, not sure if I have missed something in the instructions:
I ran the app in production mode and obtained the following alerts(confirmation messages) which I am still trying to interpret:

image

image

image

**Comment by ja-odur** [comment]
> Awesome work @ja-odur , looks like things are taking shape. :)
> 
> Just some few observations, not sure if I have missed something in the instructions:
> I ran the app in production mode and obtained the following alerts(confirmation messages) which I am still trying to interpret:
> 
> image
> 
> image
> 
> image

@Baalmart This probably caused by token mismatch (you last login could have been from a localhost meaning the stored user info would not work on production servers. This PR also uses the new auth tenancy approach so it should be well tested using the data-segregation PR.

**Comment by ja-odur** [comment]
@Baalmart These issues have been fixed.

**Review by Baalmart — APPROVED** [review]
PR functions as expected.....one has to first replace the` auth service` prod configs using the ones for the development environment when running `npm run prod-mac`

**Pull request merged**
