### PR TITLE
[Netmanager] fixing issues from previous PRs

### PR DESCRIPTION
**Pull request by OchiengPaul442**
#### Summary of Changes (What does this PR do?)
- PR  is resolving 3 issues raised.
- The issue of being unable to select countries has also been resolved in this PR for the country field in add new user modal.
- worked on the 3 dropdowns on the device registry and assigned users views and updated the dropdowns to the currently used dropdown in the project.
- Resolved the issue of the failed auto refresh on the assigned user's table when deleting a user. 
- Implemented a horizontal loader at the top to show progress during the deletion process (enhancing UX).

#### Status of maturity (all need to be checked before merging):
- [x] I've tested this locally
- [x] I consider this code done

#### Packages
- No new packages have been used in this PR.

#### NOTICE ISSUE
- ON THE DEVICE REGISTRY VIEW I NOTICE THAT YOU GET AN ERROR WHEN YOU TRY TO ADD A DEVICE. "BAD REQUEST"

#### Screenshots (optional)
image

image

Screenshot (66)

### CODE REVIEW

**Review by Baalmart — APPROVED** [review]
Solid! Thanks @OchiengPaul442 .

To quicken the feedback loop and address emerging concerns in a timely manner, I am merging this PR now to observe the corresponding behavior of the Github Actions.

Thanks again.

**Comment by Baalmart** [comment]
@OchiengPaul442 , the deployment still fails!
Check: https://github.com/airqo-platform/AirQo-frontend/actions/runs/5302653807/jobs/9597734478

On this note, we need to do 2 things as we continue to investigate this issue:

1. I am going to revert the PR, but encourage you to keep your local changes intact on your PC to easily reference your Git history.
2. After the revert I am about to do, please raise a separate PR from staging that is just introducing a new line on the READ of the Netmanager repo. **WHY?** We can use it as a test to find out if it the recent changes causing the failure OR it is just something wrong in our Github OR deployment files.

Thanks again and have a nice Sunday!

**Comment by OchiengPaul442** [comment]
Your welcome @Baalmart

**Comment by Baalmart** [comment]
@OchiengPaul442 , additionally, I am going to "cleanup" our `staging `branch.
These reverts sometimes mess up our branches.

After I am done with the "cleanup", please pull the latest staging and work from it. 

Thanks!

**Comment by OchiengPaul442** [comment]
Hey @Baalmart if your not so busy could we have a quick huddle just to check on something.

**Comment by OchiengPaul442** [comment]
> @OchiengPaul442 , additionally, I am going to "cleanup" our `staging `branch. These reverts sometimes mess up our branches.
> 
> After I am done with the "cleanup", please pull the latest staging and work from it.
> 
> Thanks!

Okay 👌

**Pull request merged**
