### PR TITLE
remove obsolete jenkins folder

### PR DESCRIPTION
**Pull request by 123MwanjeMike**
#### Summary of Changes (What does this PR do?)
- remove jenkins folder

#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [x] I consider this code done
- [x] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
- n/a

#### What are the relevant tickets?
- n/a

#### Screenshots (optional)

### CODE REVIEW

**Review by Baalmart — COMMENTED** [review]
Thanks @123MwanjeMike for this cleanup, how are we storing Jenkins configuration files now?

**Comment by 123MwanjeMike** [comment]
> Thanks @123MwanjeMike for this cleanup, how are we storing Jenkins configuration files now?

They are currently being stored in the Jenkins folder although they are no longer going to be used. This PR removes them completely since they are obsolete. @Baalmart

**Review by NoahNsimbe — APPROVED** [review]
LGTM

**Comment by Baalmart** [comment]
> > Thanks @123MwanjeMike for this cleanup, how are we storing Jenkins configuration files now?
> 
> They are currently being stored in the Jenkins folder although they are no longer going to be used. This PR removes them completely since they are obsolete. @Baalmart

Thanks for the clarification @123MwanjeMike , what do you mean by "they are no longer going to be used" Does it mean that we are no longer going to use Jenkins in our works?

**Comment by 123MwanjeMike** [comment]
> Thanks for the clarification @123MwanjeMike , what do you mean by "they are no longer going to be used" Does it mean that we are no longer going to use Jenkins in our works?

We are already using GitHub actions to do everything that was being done with Jenkins and even more. And even if we shifted back to Jenkins, these files no longer satisfy our CI/CD needs and we would have to create new ones in such a scenario.

**Comment by Baalmart** [comment]
> > Thanks for the clarification @123MwanjeMike , what do you mean by "they are no longer going to be used" Does it mean that we are no longer going to use Jenkins in our works?
> 
> We are already using GitHub Actions to do everything that was being done with Jenkins and even more. And even if we shifted back to Jenkins, these files no longer satisfy our CI/CD needs and we would have to create new ones in such a scenario. cc @Baalmart

Alright, thanks for these notes @123MwanjeMike

**Review by Baalmart — APPROVED** [review]
LGTM

**Pull request merged**
