### PR TITLE
[NetManager] Add other pollutants

### PR DESCRIPTION
**Pull request by ja-odur**
#### Summary of Changes (What does this PR do?)
- Adds access to other pollutants on NetManager map.

#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [x] I consider this code done
- [x] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* Fetch this branch locally
* Install requirements using `npm install`
* Start Application using `npm run stage-mac` (MacOs) or `npm run stage-pc` (Windows PC)
* Should be able to access all the other pollutants on netmanager map.

#### What are the relevant tickets?
- [PLAT-580](https://airqoteam.atlassian.net/browse/PLAT-580)

#### Screenshots (optional)

### CODE REVIEW

**Review by Priscilla-AL — COMMENTED** [review]
Should we wait for the improvements we discussed to be made

**Comment by ja-odur** [comment]
> Should we wait for the improvements we discussed to be made

Yes @Priscilla-AL

**Comment by ja-odur** [comment]
> Should we wait for the improvements we discussed to be made

The changes have been implemented

**Review by danielogen — APPROVED** [review]
This is working well, the widget looks great. Prehaps we can disable the heatmap once the user selects any other pollutant apart from PM2.5

**Review by sserurich — APPROVED** [review]
LGTM

**Review by Baalmart — APPROVED** [review]
LGTM

**Pull request merged**
