### PR TITLE
[WEBSITE] Clean Air Network Implementation (About page)

### PR DESCRIPTION
**Pull request by OchiengPaul442**
#### Summary of Changes (What does this PR do?)
Feature: Implementation of the Figma design for the Home/About page.

- First Draft of the Home/About page of the cleanAir Network site.
- This is just a skeleton implementation, no backend models have been implemented yet.

#### Status of maturity (all need to be checked before merging):

- [x] I've tested this locally
- [x] I consider this code done
- [ ] This change is ready to hit production in its current state

#### How should this be manually tested?
- To view the changes of this PR navigate to the About tab on the top bar and select CleanAir Network from the dropdown.

#### Screenshots (optional)
image
image

### CODE REVIEW

**Comment by Baalmart** [comment]
Hi @OchiengPaul442 , PR now has some merge conflicts which need your attention.

**Comment by OchiengPaul442** [comment]
Thanks, @Baalmart, I will look into it.

**Comment by OchiengPaul442** [comment]
All is good now @Baalmart.

**Review by Baalmart — APPROVED** [review]
Thanks @OchiengPaul442 , all looks good to me. 
I will wait for the approval of @FaithDaka before merging this PR.

**Comment by FaithDaka** [comment]
This is ready for merge @Baalmart

**Pull request merged**
