### PR TITLE
Ft sites registry

### PR DESCRIPTION
**Pull request by Codebmk**
#### Summary of Changes (What does this PR do?)

- Applies sites summary api to sites table
- Refactor site details page to only retrieve a given site's details and not check the entire list of sites

- Country, Region and District to be added to the summary api

#### Status of maturity (all need to be checked before merging):

- [x] I've tested this locally
- [x] I consider this code done
- [x] This change ready to hit production in its current state
- [x] The title of the PR states what changed and the related issues number (used for the release note).

#### How should this be manually tested?

- On deploy preview, visit /sites and the site details page. Both should load faster than production pages

#### What are the relevant tickets?

- [AN-409](https://airqoteam.atlassian.net/browse/AN-409) 

#### Screenshots (optional)
image

[AN-409]: https://airqoteam.atlassian.net/browse/AN-409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by Baalmart — APPROVED** [review]
Thanks @Codebmk

**Review by Baalmart — CHANGES_REQUESTED** [review]
Hi @Codebmk , we shall need to review the Site details page, appears that we are now no longer able to see the deployed devices to the Site. See attached screenshot for a Site which is attached to a device in devices table.

Screenshot 2023-05-11 at 23 52 59

**Comment by Codebmk** [comment]
@Baalmart which site is that?

**Comment by Baalmart** [comment]
> here

Hi @Codebmk , please check out attached screenshot.
Screenshot 2023-05-12 at 07 30 45

**Comment by Baalmart** [comment]
> > here
> 
> Hi @Codebmk , please check out attached screenshot. Screenshot 2023-05-12 at 07 30 45

But wait, @Codebmk ....I am not able to reproduce issue for some sites.
I guess we need to investigate further.
Unfortunately, I do not remember the specific Site details for the first issue!
Let me continue to investigate and share findings.

Thank you @Codebmk

**Review by Baalmart — APPROVED** [review]
Based on recent discoveries, I now approve the PR. Thanks @Codebmk

**Review by NoahNsimbe — APPROVED** [review]
LGTM

**Comment by Baalmart** [comment]
Hi @Codebmk we now have some merge conflicts to resolve....

**Pull request closed without merging**
