### PR TITLE
move to production

### PR DESCRIPTION
**Pull request by Baalmart**
#### Summary of Changes (What does this PR do?)
- move to production

### CODE REVIEW

**Review by NoahNsimbe — APPROVED** [review]
LGTM

**Review by BenjaminSsempala — APPROVED** [review]
LGTM

**Review by NoahNsimbe — CHANGES_REQUESTED** [review]
hi @Baalmart 
Add https://github.com/airqo-platform/AirQo-frontend/pull/686

**Review by Mnoble-19 — APPROVED** [review]
LGTM

**Pull request merged**
