### PR TITLE
Ft get app section

### PR DESCRIPTION
**Pull request by FaithDaka**
#### Summary of Changes (What does this PR do?)
- Design and implementation of get-app section for both web and mobile views.

#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [x] I consider this code done
- [x] I've tested this locally
- [x] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* The _tag_  **GetApp/>**  should be added to the _HomePage_ file to be able to view changes.

#### What are the relevant tickets?
- [WEB-129]

#### Screenshots
Web-view
Screenshot (46)

Mobile-View
Screenshot (47)

Screenshot (48)

[WEB-129]: https://airqoteam.atlassian.net/browse/WEB-129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by 123MwanjeMike — APPROVED** [review]
LGTM

**Review by ja-odur — CHANGES_REQUESTED** [review]
I see the package-lock.json is deleted. Any reasons?

**Comment by FaithDaka** [comment]
> I see the package-lock.json is deleted. Any reasons?

I didn't delete it, and it still exists on my local branch. I can't explain that.

**Review by Codebmk — APPROVED** [review]

**Review by ja-odur — APPROVED** [review]
LGTM

**Pull request merged**
