### PR TITLE
[WEBSITE] Clean Air Resources model

### PR DESCRIPTION
**Pull request by FaithDaka**
#### Summary of Changes (What does this PR do?)

- Updated the attributes of the clean air resources backend model
- Added Backend documentation

#### Status of maturity (all need to be checked before merging):

- [x] I've tested this locally
- [x] I consider this code done
- [x] This change ready to hit production in its current state
- [x] The title of the PR states what changed and the related issues number (used for the release note).
- [ ] I've included issue number in the "Closes #ISSUE-NUMBER" part of the "[What are the relevant tickets?](#what-are-the-relevant-tickets)" section to [link the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [x] I've updated corresponding documentation for the changes in this PR.
- [x] I have written unit and/or e2e tests for my change(s).

#### How should this be manually tested?

- In the admin portal, add a clean-air resource for the entry to be added to the database.

#### What are the relevant tickets?

- Closes #<enter issue number here>
- [Jira_card_number]() (If exists)

### CODE REVIEW

**Comment by FaithDaka** [comment]
@OchiengPaul442 Create an entry in the `CLEAN-Air Resources` table and confirm if it has all the attributes required in the frontend.

**Comment by OchiengPaul442** [comment]
Hey @FaithDaka,
I noticed that when creating a new resource, there’s no option to select the resource category and the author field is missing. Additionally, an error occurs during the creation process.
image

**Comment by Baalmart** [comment]
> Hey @FaithDaka, I noticed that when creating a new resource, there’s no option to select the resource category and the author field is missing. Additionally, an error occurs during the creation process. image

thanks @FaithDaka , things are taking a very good shape. It looks like there is this pending issue which needs your review. Thanks again!

**Comment by FaithDaka** [comment]
@OchiengPaul442 @Baalmart 
Changes don't reflect in this deploy preview because there's more than website PR open. Test this PR locally and provide comments @OchiengPaul442 

image

**Comment by OchiengPaul442** [comment]
okay

**Pull request merged**
