### PR TITLE
[NetManager] D3 integration part 3

### PR DESCRIPTION
**Pull request by ja-odur**
#### Summary of Changes (What does this PR do?)
- Grouped customisable bar charts (prevent stacking of bar charts behind each other)
- Enable downloading of customisable charts
- Fix customisable chart labels (add subscripts and superscripts on the labels according)

#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [x] I consider this code done
- [ ] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* Fetch and checkout to this branch locally
* Install requirements `npm install`
* Start netmanager staging application `npm run stage`
* Confirm the summary of changes listed above

#### What are the relevant tickets?
- [PLAT-937](https://airqoteam.atlassian.net/browse/PLAT-937)

### CODE REVIEW

**Review by 123MwanjeMike — COMMENTED** [review]
LGTM

**Comment by Codebmk** [comment]
@ja-odur this branch is not up-to-date. Won't that cause trouble during merging?

**Comment by ja-odur** [comment]
> @ja-odur this branch is not up-to-date. Won't that cause trouble during merging?

@Codebmk This should not cause any trouble as long as there are no merge conflicts. But let me rebase and reword the setup.

**Comment by ja-odur** [comment]
@Codebmk I have updated the branch.

**Comment by Codebmk** [comment]
@ja-odur On my end, the bar charts seems to be stacked behind each other. If possible, please share a screenshot of what the charts should look like.

chart

**Comment by Codebmk** [comment]
> 

Eh! The summary of changes definitely wasn't clear

**Review by Baalmart — COMMENTED** [review]
I have failed to switch chartTypes, as seen in the attached screenshots. @ja-odur 
Screenshot 2022-02-11 at 11 51 09
Screenshot 2022-02-11 at 11 55 33

**Comment by ja-odur** [comment]
> I have failed to switch chartTypes, as seen in the attached screenshots. @ja-odur Screenshot 2022-02-11 at 11 51 09 Screenshot 2022-02-11 at 11 55 33

This is also failing on my end. Let me look into it.

**Pull request merged**
