### PR TITLE
[NetManager] Hot-fix Loading of dashboard user defaults

### PR DESCRIPTION
**Pull request by ja-odur**
#### Summary of Changes (What does this PR do?)
- fix loading of dashboard user defaults
#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [x] I consider this code done
- [x] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

Good to have (up to reviewer's discretion):
- [ ] I've tested this on staging
- [ ] Unit test coverage of changes

#### How should this be manually tested?
* Pull and checkout to this [branch]() locally
* Install node requirements `npm install`
* Start the application `npm run prod-mac` (on mac) or `npm run prod-pc` (on windows platform)
* You should able to load the dashboards and set custom graphs without the paging freezing
#### What are the relevant tickets?
- [None]()

#### Screenshots (optional)

### CODE REVIEW

**Review by lilly-muyama — COMMENTED** [review]
I get this error when I tried custimizing the chart by changing the locations
Capture

**Review by Baalmart — COMMENTED** [review]
When I try to reload or logout, the defaults revert to the general ones.

**Comment by ja-odur** [comment]
> When I try to reload or logout, the defaults revert to the general ones.

@Baalmart you maybe using prod. You can manually tweak the default url to point to staging i.e. port 31000 while running production version.

**Review by Baalmart — APPROVED** [review]

**Comment by ja-odur** [comment]
> I get this error when I tried customizing the chart by changing the locations
> Capture

@lilly-muyama in which environment was this?

**Pull request merged**
