### PR TITLE
[NETMANAGER] Display organization details

### PR DESCRIPTION
**Pull request by OchiengPaul442**
#### Summary of Changes (What does this PR do?)

feature: Added view and edit functionality for organization details

- Introduced a view for organization details under the organization page, allowing authorized users to edit the details of the organization.
- Included a drawer to display additional information about the organization description and reduce table congestion.
- There is a reload of the page after creating or editing an organization to ensure changes take full effect.

#### Notice:
Please be aware that there is currently a small issue with the display of newly created organizations for users on the sidebar dropdown. This issue is under investigation and we are working to resolve it as soon as possible.

#### Status of maturity (all need to be checked before merging):

- [X] I've tested this locally
- [X] I consider this code done
- [X] This change ready to hit production in its current state

#### How should this be manually tested?

- To view the changes on this PR navigate to the organisation page

- [AN-470](https://airqoteam.atlassian.net/browse/AN-470) 

#### Screenshots (optional)
image
image
image
image

[AN-470]: https://airqoteam.atlassian.net/browse/AN-470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by Baalmart — CHANGES_REQUESTED** [review]
Thanks @OchiengPaul442 for this. This is very encouraging!

1. Using **attached screenshots**, I have left some comments for your review. 
2. Additionally, please continue unit testing accordingly.
cc: @Codebmk 
Screenshot 2023-09-07 at 18 15 24
Screenshot 2023-09-07 at 18 16 00
Screenshot 2023-09-07 at 18 17 35
Screenshot 2023-09-07 at 18 18 48

**Comment by OchiengPaul442** [comment]
Hey @Baalmart, thank you for your feedback. 
1. The pop-up windows and models have been designed to accommodate additional fields while maintaining a fixed height. If necessary, they can be scrolled while still keeping the user interface neat.
2. The use of pop-ups will help us reduce the number of files created and make the folder structure cleaner.
cc: @Codebmk 
3. Will work on the other changes suggested.
Thanks.

**Comment by Baalmart** [comment]
Thanks @OchiengPaul442 for the clarifications. It makes sense now.

**Comment by Baalmart** [comment]
@OchiengPaul442 I do notice that the PR has some merge conflicts in it?

**Comment by OchiengPaul442** [comment]
Hey @Baalmart, I have not yet updated this branch with the latest change from staging that's what's causing the conflicts.

**Comment by OchiengPaul442** [comment]
All should be good now @Baalmart.

**Comment by Baalmart** [comment]
> All should be good now @Baalmart.

thanks @OchiengPaul442 , let me check it out

**Comment by Baalmart** [comment]
Hi @OchiengPaul442  
I have just realised that the latest changes from staging blocked this ORGANISATIONS functionality from the side bar.

**What is the best way forward?**

1. Should we temporarily enable the option for testing this PR?
2. Or should we just put this PR in DRAFT mode until we completely sort out this ORGANISATION dilemma from the backend?

**Comment by OchiengPaul442** [comment]
Good afternoon @Baalmart, Given that there are still some issues I think it's best to first keep it as a Draft as we sort out the organization staff in the backend and sync with the frontend then test fully.

**Comment by Baalmart** [comment]
Alright @OchiengPaul442 please change the status of this PR accordingly

**Comment by OchiengPaul442** [comment]
Okay

**Pull request closed without merging**
