### PR TITLE
Proof-read App Privacy Policy

### PR DESCRIPTION
**Pull request by BenjaminSsempala**
#### Summary of Changes (What does this PR do?)
- The content on [Mobile Application Privacy Policy](https://docs.airqo.net/airqo-application-documentations/) does not seem to match the one on [Docs](https://staging-docs.airqo.net/#/mobile_app/privacy_policy). 
Goal: Update the content on [Docs](https://staging-docs.airqo.net/#/mobile_app/privacy_policy) to reflect the what is on [Mobile Application Privacy Policy](https://docs.airqo.net/airqo-application-documentations/)
- [x] Added email in  the `contact us` section.
- [x] Correct misspelt words.

#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [x] I consider this code done
- [x] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* Proof read or cross-check through the content on [Mobile Application Privacy Policy](https://docs.airqo.net/airqo-application-documentations/) and the one on [Docs](https://staging-docs.airqo.net/#/mobile_app/privacy_policy). 

#### What are the relevant tickets?
- [MOB-132](https://airqoteam.atlassian.net/browse/MOB-132)

#### Screenshots (optional)

### CODE REVIEW

**Review by 123MwanjeMike — APPROVED** [review]
Thanks @BenjaminSsempala for catching this.
LGTM

**Review by NoahNsimbe — COMMENTED** [review]
Thanks @BenjaminSsempala . Last updated seems to be missing.

Screenshot 2022-11-08 at 12 27 53

**Comment by BenjaminSsempala** [comment]
> Thanks @BenjaminSsempala . Last updated seems to be missing.
> 
> Screenshot 2022-11-08 at 12 27 53

Thank you @NoahNsimbe 
I've updated it now Thanks.

**Review by NoahNsimbe — APPROVED** [review]
LGTM

**Review by Baalmart — APPROVED** [review]
LGTM

**Pull request merged**
