### PR TITLE
[NetManager] Crud operations plat 464

### PR DESCRIPTION
**Pull request by ja-odur**
#### Summary of Changes (What does this PR do?)
- Implements CRUD operations for devices, maintenance logs and device components
- Redesign the maintenance and components sections of device overview

#### Is this change ready to hit production in its current state?
- [ ] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [ ] I consider this code done
- [ ] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* `npm install`
* `npm run stage-mac` (macOS) or `npm run stage-dev` (Windows platform)

#### What are the relevant tickets?
- [PLAT-464](https://airqoteam.atlassian.net/browse/PLAT-464)

#### Screenshots (optional)

### CODE REVIEW

**Review by danielogen — COMMENTED** [review]
All functionalities are working well expect `refreshing page` after the delete operation

**Comment by ja-odur** [comment]
> All functionalities are working well expect `refreshing page` after the delete operation

@danielogen This has been fixed. please test again.

**Review by danielogen — APPROVED** [review]
LGTM

**Review by Baalmart — APPROVED** [review]
LGTM

**Pull request merged**
