### PR TITLE
Adding compressed images

### PR DESCRIPTION
**Pull request by Mnoble-19**
#### Summary of Changes (What does this PR do?)
- Adding compressed images

#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [x] I consider this code done
- [x] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* Get the branch locally
* Run the app with flutter run

#### Screenshots (optional)

### CODE REVIEW

**Review by BenjaminSsempala — APPROVED** [review]
LGTM

**Review by 123MwanjeMike — APPROVED** [review]
LGTM

**Review by NoahNsimbe — CHANGES_REQUESTED** [review]
Hi @Mnoble-19 . Thanks. 
I notice the images are `jpg`. The app will never find these images because it expects `png` 
(Screenshot attached). You can consider either the following options.

- Make the images png
- Update the app code base. 

Screenshot 2022-11-10 at 12 57 05

**Comment by Mnoble-19** [comment]
Thanks for catching that @NoahNsimbe. 
I'd just added them as I got them
Think it's all good now. 

splash_screen

**Review by NoahNsimbe — APPROVED** [review]
LGTM

**Review by NoahNsimbe — CHANGES_REQUESTED** [review]
Hi @Mnoble-19,
Any reason for using a different folder?? `Images != images`

**Pull request closed without merging**
