### PR TITLE
DevOps - Platform Deployment

### PR DESCRIPTION
**Pull request by danielogen**
**1. What does this PR do?**
This PR resolves issues related to `platform` deployment - 404 errors on page hard refresh of every page
**2. What JIRA task is related to this PR?**
The link to the JIRA board task is [here](https://airqoteam.atlassian.net/browse/PLAT-110).
**3. How do I test out this PR?**
Git clone this repo `cd AirQo-frontend/netmanager`. Then run `npm install` to get all the necessary dependencies. Afterwards, use docker to test out this PR as follows: run (1) `npm run build`,  (2) `docker build -t us.gcr.io/airqo-250220/airqo-stage-netmanager-frontend .`, (3) `docker run -d -p 8888:80 us.gcr.io/airqo-250220/airqo-stage-netmanager-frontend`. Point your browser to `localhost:8888/login` to test out the service. 
NB: Change port `8888` to any port number of your choosing or don't :).

### CODE REVIEW

**Review by Baalmart — COMMENTED** [review]
Just tried to test out but getting the following message (see screenshot below). 
image

I have followed all the PR instructions to the dot. Could I have missed something in the instructions?

**Comment by danielogen** [comment]
> Just tried to test out but getting the following message (see screenshot below).
> image
> 
> I have followed all the PR instructions to the dot. Could I have missed something in the instructions?

I am not sure. For now, try adding `SKIP_PREFLIGHT_CHECK=true` flag to your `.env` file.

**Comment by Baalmart** [comment]
> SKIP_PREFLIGHT_CHECK=true

no change, just added this to the env, then stopped the image, created a new one and still received the same response.

**Review by lilly-muyama — COMMENTED** [review]
I can't get past  npm run build 
Capture

**Comment by danielogen** [comment]
> I can't get past npm run build
> Capture

An issue is created here: https://github.com/airqo-platform/AirQo-frontend/issues/133. Since its a general challenge, we are looking at possible solutions.

**Comment by danielogen** [comment]
This was resolved in this sprint, so I will delete this PR. cc: @Baalmart , @lilly-muyama , @ja-odur

**Pull request closed without merging**
