### PR TITLE
[NetManager] Add AirQo devices to map

### PR DESCRIPTION
**Pull request by ja-odur**
#### Summary of Changes (What does this PR do?)
- Adds AirQo devices to map. Before the would would only show KCCA devices regardless whether you're logged into AirQo organisation.

#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [x] I consider this code done
- [x] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* Fetch this branch locally
* Install requirements using `npm install`
* Start Application using `npm run stage-mac` (MacOs) or `npm run stage-pc` (Windows PC)
* In case this [PR](https://github.com/airqo-platform/AirQo-api/pull/336) is not yet merged and deployed, you need to set it up locally and manually change the staging `EVENTS` key in the `constants.js` file (NetManager) to point to the locally running `device-registry` micro-service.
* Log into AirQo organisation, you be able to access AirQo devices on the map (accessed through the sidebar tab "Map")

#### What are the relevant tickets?
- [PLAT-485](https://airqoteam.atlassian.net/browse/PLAT-485)

#### Screenshots (optional)

### CODE REVIEW

**Review by Priscilla-AL — COMMENTED** [review]
Error: An API access token is required to use Mapbox GL. See https://www.mapbox.com/api-documentation/#access-tokens-and-token-scopes
▼ 6 stack frames were expanded.
G._makeAPIURL
C:/Users/User/Documents/Projects/AirQo-frontend/netmanager/node_modules/mapbox-gl/dist/mapbox-gl.js:31
G.normalizeStyleURL
C:/Users/User/Documents/Projects/AirQo-frontend/netmanager/node_modules/mapbox-gl/dist/mapbox-gl.js:31
i.loadURL
C:/Users/User/Documents/Projects/AirQo-frontend/netmanager/node_modules/mapbox-gl/dist/mapbox-gl.js:35
r._updateStyle
C:/Users/User/Documents/Projects/AirQo-frontend/netmanager/node_modules/mapbox-gl/dist/mapbox-gl.js:35
r.setStyle
C:/Users/User/Documents/Projects/AirQo-frontend/netmanager/node_modules/mapbox-gl/dist/mapbox-gl.js:35
new r
C:/Users/User/Documents/Projects/AirQo-frontend/netmanager/node_modules/mapbox-gl/dist/mapbox-gl.js:35
▲ 6 stack frames were expanded.
(anonymous function)
C:/Users/User/Documents/Projects/AirQo-frontend/netmanager/src/views/pages/Map/OverlayMap.js:76
  73 |  });
  74 | 
  75 |  useEffect(() => {
> 76 |    const map = new mapboxgl.Map({
     | ^  77 |      container: mapContainerRef.current,
  78 |      style: "mapbox://styles/mapbox/streets-v11",
  79 |      // style: "mapbox://styles/mapbox/dark-v10",
View compiled
▶ 13 stack frames were collapsed.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.

**Comment by ja-odur** [comment]
> Error: An API access token is required to use Mapbox GL. See https://www.mapbox.com/api-documentation/#access-tokens-and-token-scopes
> ▼ 6 stack frames were expanded.
> G._makeAPIURL
> C:/Users/User/Documents/Projects/AirQo-frontend/netmanager/node_modules/mapbox-gl/dist/mapbox-gl.js:31
> G.normalizeStyleURL
> C:/Users/User/Documents/Projects/AirQo-frontend/netmanager/node_modules/mapbox-gl/dist/mapbox-gl.js:31
> i.loadURL
> C:/Users/User/Documents/Projects/AirQo-frontend/netmanager/node_modules/mapbox-gl/dist/mapbox-gl.js:35
> r._updateStyle
> C:/Users/User/Documents/Projects/AirQo-frontend/netmanager/node_modules/mapbox-gl/dist/mapbox-gl.js:35
> r.setStyle
> C:/Users/User/Documents/Projects/AirQo-frontend/netmanager/node_modules/mapbox-gl/dist/mapbox-gl.js:35
> new r
> C:/Users/User/Documents/Projects/AirQo-frontend/netmanager/node_modules/mapbox-gl/dist/mapbox-gl.js:35
> ▲ 6 stack frames were expanded.
> (anonymous function)
> C:/Users/User/Documents/Projects/AirQo-frontend/netmanager/src/views/pages/Map/OverlayMap.js:76
> 73 | });
> 74 |
> 75 | useEffect(() => {
> 
> > 76 |    const map = new mapboxgl.Map({
> > | ^  77 |      container: mapContainerRef.current,
> > 78 |      style: "mapbox://styles/mapbox/streets-v11",
> > 79 |      // style: "mapbox://styles/mapbox/dark-v10",
> > View compiled
> > ▶ 13 stack frames were collapsed.
> > This screen is visible only in development. It will not appear if the app crashes in production.
> > Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.

I have shared the `.env` on slack

**Review by lilly-muyama — APPROVED** [review]
Works as expected

**Review by Priscilla-AL — APPROVED** [review]
LGTM

**Review by NoahNsimbe — APPROVED** [review]
LGTM

**Pull request merged**
