### PR TITLE
Ft get involved

### PR DESCRIPTION
**Pull request by Codebmk**
#### Summary of Changes (What does this PR do?)
- Implemented responsiveness

#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [x] I consider this code done
- [ ] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* Do a git fetch and then checkout to this local branch to run.

#### What are the relevant tickets?
- [WEB-161](https://airqoteam.atlassian.net/browse/WEB-161)

#### Screenshots
getInvolved-1
getInvolved-2
getInvolved-3

### CODE REVIEW

**Comment by ja-odur** [comment]
@Codebmk you might want to add some left and right padding to this section containing text
image

**Review by ja-odur — COMMENTED** [review]
This as well
image

**Comment by Codebmk** [comment]
> This as well image

@ja-odur I have added those changes

**Review by ja-odur — APPROVED** [review]
LGTM

**Pull request merged**
