### PR TITLE
Website ingress resource

### PR DESCRIPTION
**Pull request by NoahNsimbe**
#### Summary of Changes (What does this PR do?)

- [x] Configurations for the website ingress resource [staging]
- [x] Renaming files

#### Is this change ready to hit production in its current state?
- [ ] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [ ] I consider this code done
- [ ] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* Visit https://staging.airqo.net/

### CODE REVIEW

**Review by 123MwanjeMike — APPROVED** [review]
LGTM
Thanks @NoahNsimbe

**Review by danielogen — APPROVED** [review]
Great work @NoahNsimbe

**Comment by danielogen** [comment]
Now we just have to work on SSL certs the above domain(s)

**Comment by danielogen** [comment]
Also,
The website view on large screen leaves some empty space on the right

Screen Shot 2022-03-17 at 9 13 48 AM
cc: @ja-odur

**Pull request merged**
