### PR TITLE
[NetManager] Service desk issues

### PR DESCRIPTION
**Pull request by ja-odur**
#### Summary of Changes (What does this PR do?)
- Add timer on notification banner to auto-close
- Grey-out offline devices
- issues fixed [253](https://github.com/airqo-platform/AirQo-frontend/issues/253) [245](https://github.com/airqo-platform/AirQo-frontend/issues/245) [84](https://github.com/airqo-platform/AirQo-frontend/issues/84)

#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [x] I consider this code done
- [ ] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* Fetch this branch locally
* Install requirements using `npm install`
* Start Application using `npm run stage-mac` (MacOs) or `npm run stage-pc` (Windows PC)
* Verify the issues above are fixed.

#### What are the relevant tickets?
- [ticket_id]()

#### Screenshots (optional)

### CODE REVIEW

**Review by danielogen — APPROVED** [review]
This is working perfectly fine on my end.

**Review by Priscilla-AL — APPROVED** [review]
works as expected.

**Review by sserurich — CHANGES_REQUESTED** [review]
All items work perfectly as expected, except [issue](https://github.com/airqo-platform/AirQo-frontend/issues/84), couldn't comfirm that and instead got some other errors while trying to reproduce it as shown in these two issues  i.e. [login](https://github.com/airqo-platform/AirQo-frontend/issues/255) &[ request access](https://github.com/airqo-platform/AirQo-frontend/issues/256)

**Review by sserurich — APPROVED** [review]
the raised issue will be addressed since are documented.

**Pull request merged**
