### PR TITLE
[WEBSITE] Events Model and dynamic frontend

### PR DESCRIPTION
**Pull request by FaithDaka**
#### Summary of Changes (What does this PR do?)

- Events model including program, sessions, inquiries and partner logos.
- Events redux state management
- Dynamic events page and featured section
- Dynamic events details page 

#### Status of maturity (all need to be checked before merging):

- [x] I've tested this locally
- [x] I consider this code done
- [x] This change ready to hit production in its current state
- [x] The title of the PR states what changed and the related issues number (used for the release note).

#### How should this be manually tested?

- View events page in deploy preview.
- Interact with the various events to view dynamic components

#### What are the relevant tickets?

- [WEB-367]

#### Screenshots (optional)

[WEB-367]: https://airqoteam.atlassian.net/browse/WEB-367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by 123MwanjeMike — CHANGES_REQUESTED** [review]
Hi @FaithDaka 
The deploy preview seems to be failing because of the error below. Could there be some dependencies not added to the requirements.txt file?

image
image

**Comment by FaithDaka** [comment]
Maybe upgrading?

**Review by Codebmk — APPROVED** [review]
Amazing work @FaithDaka LGTM
image
Screenshot from 2023-03-17 11-12-40
Screenshot from 2023-03-17 11-12-14
image

**Comment by 123MwanjeMike** [comment]
> @123MwanjeMike Do the various deployments include a "_python manage.py collectstatic_" command. It will be required for the _django-quill-editor_ package

Yes they're @FaithDaka

**Review by Baalmart — APPROVED** [review]
Good stuff! Thanks @FaithDaka !

**Pull request merged**
