### PR TITLE
[NET] Adding feature to add new device hosts, and send them mobile money

### PR DESCRIPTION
**Pull request by OchiengPaul442**
#### Summary of Changes (What does this PR do?)

feature: Add ability to register new device hosts and send mobile money
-This commit implements the functionality to add new device hosts and send them mobile money. This allows users to easily manage their device hosts and make mobile money transactions.

### New changes
- Refactored the HostView
- Removed the Hosts tab from the device registry
- Refactored the edit modal
- Updated hosts table to display only hosts for a specified organization/network

#### Status of maturity (all need to be checked before merging):

- [x] I've tested this locally
- [x] I consider this code done
- [x] This change ready to hit production in its current state

- [Jira_card_number]() (https://airqoteam.atlassian.net/browse/AN-513)

#### Screenshots (optional)
image
image
image
image

### CODE REVIEW

**Review by Baalmart — CHANGES_REQUESTED** [review]
Thanks @OchiengPaul442 ....we might want to reconsider the design side of things......

1. We might want to just create a new **sidebar item** called `Hosts Registry.`...just like how we have Device. Site and AirQlouds Registry.
2. After creating that side bar item, we shall want to now link this host to the device by just listing them under each device details page and providing a way a user can click on that host to be led back to "Host Registry".
3. Also please notes that creating a Host requires a Site ID......perhaps we need to reconsider this design decision in the API? And making changes accordingly? I am open to suggestions.
4. We could also have a short meeting about this on any weekday (next week) in the late evening hours to review how the UI mockup side of things.

Thanks!
Screenshot 2023-08-12 at 20 53 34

**Comment by OchiengPaul442** [comment]
Thank you for your feedback, @Baalmart. I included the SITE ID as a hidden field that is not visible to the users since it’s a value that doesn’t need to be changed. However, I’m not sure how the backend works yet still working on understanding it better but I believe that once a device has been deployed to a site, it’s given a site ID that is an object of around 24 characters. I thought including this identifier was pointless since the user won’t need to change it, but I stand to be corrected.

Thanks.

**Comment by Baalmart** [comment]
> Thank you for your feedback, @Baalmart. I included the SITE ID as a hidden field that is not visible to the users since it’s a value that doesn’t need to be changed. However, I’m not sure how the backend works yet still working on understanding it better but I believe that once a device has been deployed to a site, it’s given a site ID that is an object of around 24 characters. I thought including this identifier was pointless since the user won’t need to change it, but I stand to be corrected.
> 
> Thanks.

thanks for the clarification @OchiengPaul442 .....I guess I now need to rethink my feedback! :) 

- So please forget about the identifier then but just change the message to something more user friendly....more like this device has not yet been deployed...better still, just disable the Host Addition for devices which are not yet deployed and inform the user accordingly why the option is disabled.
- A quick follow up question....how does one see the list of Hosts in the system?
- Lastly and most importantly, do not worry about understanding everything since we are all just figuring out stuff as we work. :)

**Comment by OchiengPaul442** [comment]
@Baalmart. I will make the suggested change. Currently, users are unable to see a list of all Hosts on the system. The implemented feature only allows users to see hosts for a device based on the site_id. However, as you suggested, we can include a new item on the sidebar to show a list of all Hosts in the system.

Thanks.

**Review by Baalmart — COMMENTED** [review]
Hi @OchiengPaul442 Because of our conversation we have had here, I have just pieced together a couple of documentations and sent then to you via email. Please check them out asap and let me know if you have any more clarifications.

Thanks!

**Comment by OchiengPaul442** [comment]
Thanks @Baalmart, for your clear explanation in the email. Everything is well understood and I will proceed with the implementation as planned.

**Comment by Baalmart** [comment]
Alright @OchiengPaul442 glad that everything is now clear. 🤝

**Comment by OchiengPaul442** [comment]
@Baalmart @Codebmk , the PR is ready for review.
Thanks.

**Comment by Baalmart** [comment]
> here

thanks @OchiengPaul442

**Review by Baalmart — CHANGES_REQUESTED** [review]
Hi @OchiengPaul442 , this is great work and progress.
Just one quick feedback in form a screenshot.
Screenshot 2023-08-23 at 14 25 33

**Review by Codebmk — CHANGES_REQUESTED** [review]
Amazing work here @OchiengPaul442 .

All looks good except this one thing.

The send and edit buttons need to be disabled once the client hits send and the api is now handling the transaction.
image

**Comment by OchiengPaul442** [comment]
> Amazing work here @OchiengPaul442 .
> 
> All looks good except this one thing.
> 
> The send and edit buttons need to be disabled once the client hits send and the api is handling the transaction. image

Thanks, will work on that.

**Comment by OchiengPaul442** [comment]
Thanks for your feedback @Baalmart and @Codebmk , will continue making the necessary changes.

@Baalmart I have noticed a bit of a slow response on both Postman and frontend implementation when it comes to sending mobile money to the desired host. 
- It kind of takes too long to respond maybe some optimization can be done to solve that.
Thanks



-

**Comment by Codebmk** [comment]
@OchiengPaul442 I also noticed that there is no alert tells the user whether the transaction was successful or not. True about the API response being very slow.

**Review by Codebmk — APPROVED** [review]
LGTM @OchiengPaul442 . Much thanks!

**Review by Baalmart — APPROVED** [review]

**Pull request merged**
