### PR TITLE
[NETMANAGER] Heatmap Reconfiguration

### PR DESCRIPTION
**Pull request by FaithDaka**
#### Summary of Changes (What does this PR do?)

- Updates to _predict_ endpoint configuration
- Functionality added to loop through endpoint and return all paginated objects
- Refactored additional frontend logic to match the backend. 
- Heatmap objects no longer created on the client-side

#### Status of maturity (all need to be checked before merging):

- [x] I've tested this locally
- [x] I consider this code done
- [x] This change ready to hit production in its current state
- [x] The title of the PR states what changed and the related issues number (used for the release note).

#### How should this be manually tested?

- View heatmap in deploy preview. Currently works with **production** API data

#### Screenshots
image

### CODE REVIEW

**Review by Baalmart — COMMENTED** [review]
Thanks @FaithDaka for this, much appreciated! :)
I will just leave a few comments:

1. I noticed that the heatmap checkbox is enabled by default. Have we put in place mechanisms to ensure that the current instabilities we are still solving do not "interfere" with other relatively stable functionalities?
2. I seem to be getting some CORS errors. See **attached screenshots** for review.

Thanks again! Looking forward to your feedback towards my few observations.

Screenshot 2023-06-29 at 13 50 47
Screenshot 2023-06-29 at 13 50 51

**Comment by FaithDaka** [comment]
Thanks @Baalmart 
Let me look into the CORS issue and see if anything can be done on the frontend. At the time of implementation, the _predict_ API endpoint was stable.

For comment 1: The heatmap was requested to show by default from user feedback. But the issue at the time was: the heatmap objects were being created from the client-side which took quite a long time and used a lot of client resources. But since the heatmap objects are now coming from the server, then it can show by default.

**Comment by Baalmart** [comment]
> Thanks @Baalmart Let me look into the CORS issue and see if anything can be done on the frontend. At the time of implementation, the _predict_ API endpoint was stable.
> 
> For comment 1: The heatmap was requested to show by default from user feedback. But the issue at the time was: the heatmap objects were being created from the client-side which took quite a long time and used a lot of client resources. But since the heatmap objects are now coming from the server, then it can show by default.

thanks @FaithDaka , apologies....seeing this response rather late.
Just to clarify.....will this change have any effect on performance? In other words, will it in any way cause the users to wait for long for the nodes to appear on the map at any point in time.

My BIGGEST worry is that we have NEVER had any stable version of this endpoint so I have many trust issues at the moment. :)

**Comment by Baalmart** [comment]
Hi @FaithDaka , 
Unless we are doing some proper error handling for these "work in progress" ML solutions, I suggest that we just disable the **default** heat map part for the time being. And then we merge this PR.
Looking forward to your action/feedback.

**Comment by FaithDaka** [comment]
The default heatmap has been disabled @Baalmart

**Review by Baalmart — CHANGES_REQUESTED** [review]
Thanks @FaithDaka .....
We shall also need unit tests for this PR as we continue to embrace the practice throughout. Thanks! cc: @Mnoble-19

**Pull request merged**
