### PR TITLE
added back to top button

### LINKED ISSUE #844: Add a back-to-top feature on the AirQo docs
**Is your feature request related to a problem? Please describe.**
When users are accessing the documentation, users can struggle to scroll back to the start of a given page.

**Describe the solution you'd like**
We would like the users to simply click an icon and they are taken straight to the top of a page without having to manually scroll.

**Additional context**
The [AirQo docs](https://staging-docs.airqo.net/#/) source files can be found [here](https://github.com/airqo-platform/AirQo-frontend/tree/staging/docs)

### PR DESCRIPTION
**Pull request by saipranithswargam**
#### Summary of Changes (What does this PR do?)
- added a button which takes user back to top of the page
- have verified locally by running
- Closes #844 

#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [x] I consider this code done
- [x] I've tested this locally
- [x] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* Run **yarn run docker:build** to build the changes into a container
* Run **yarn run docker:cli** to run the container.
* Access [http://localhost:3000](http://localhost:3000/)
* Click the **Top** icon in the bottom right corner.
* You should be taken to the start of the page.

#### What are the relevant tickets?
- #844 

#### Screenshots (optional)
image

### CODE REVIEW

**Review by 123MwanjeMike — CHANGES_REQUESTED** [review]
Thank you @saipranithswargam.
However, could we have the button responsive on all screens.
Also, could we have the button scroll to the top of the respective page and not go to the landing page.

I have the suggestion of the [docsify-scroll-to-top](https://www.npmjs.com/package/docsify-scroll-to-top) plugin whose source code can be found [here](https://github.com/zhengxiangqi/docsify-scroll-to-top). I think it is an easier approach you could consider.

image

**Comment by saipranithswargam** [comment]
@123MwanjeMike  sure will make the necessary changes but i need some time to do this as iam a bit occupied with my exams

**Comment by 123MwanjeMike** [comment]
No worries @saipranithswargam

**Comment by 123MwanjeMike** [comment]
Hi @saipranithswargam 
I've updated the changes with the use of a back-to-top plugin

**Review by 123MwanjeMike — APPROVED** [review]

**Review by Baalmart — APPROVED** [review]
LGTM

**Pull request merged**
