### PR TITLE
[WEBSITE] Addressing User Feedback

### PR DESCRIPTION
**Pull request by FaithDaka**
#### Summary of Changes (What does this PR do?)

- Addition of prominent `clean-air network` tab to topbar nav.
- Added new clean-air partner types to partner backend.
- Refactored styling of top-bar elements
- Added SEO for clean-air about page
- Cleaned up clean-air website lifecycle and error handling
- Added filtering of partners for the airqo main site
- Added new clean-air content

#### Status of maturity (all need to be checked before merging):

- [x] I've tested this locally
- [x] I consider this code done
- [x] This change ready to hit production in its current state
- [x] The title of the PR states what changed and the related issues number (used for the release note).
- [ ] I've included issue number in the "Closes #ISSUE-NUMBER" part of the "[What are the relevant tickets?](#what-are-the-relevant-tickets)" section to [link the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [x] I've updated corresponding documentation for the changes in this PR.
- [ ] I have written unit and/or e2e tests for my change(s).

#### How should this be manually tested?

- View the clean-air tab on the topbar nav

#### What are the relevant tickets?

- Closes #<enter issue number here>
- [Jira_card_number]() (If exists)

#### Screenshots 
image
image

### CODE REVIEW

**Review by Baalmart — COMMENTED** [review]
This looks good, thanks @FaithDaka !

In relation to earlier conversations about "system design" and "architectural design" which both Zana and you are championing, please review the attached screenshot and share your feedback accordingly.

Thanks!
Screenshot 2023-10-26 at 12 30 41

**Comment by FaithDaka** [comment]
@Baalmart The button design is from the design system, if you explore the the `AirQo Design System/Buttons` file on Figma.
image

Having two dark blue buttons at the top gave an overpowering UI, and having the button with a light blue background didn't provide the emphasis that was being requested. So if you have other design elements you'd like to incorporate into that button, please share them.

**Comment by Baalmart** [comment]
> here

thanks @FaithDaka  for the clarifications.

**Review by Baalmart — APPROVED** [review]
thanks @FaithDaka

**Pull request merged**
