### PR TITLE
Add Helm charts for k8s deployed applications

### PR DESCRIPTION
**Pull request by 123MwanjeMike**
#### Summary of Changes (What does this PR do?)
- Adds Helm charts for k8s deployed applications
 
#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):
- [x] I consider this code done
- [x] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* For any of the helm charts, simply install it with `helm install <<chart path of choice>> -f <<values-file-path-of-choise>>`

#### What are the relevant tickets?
- [PLATOPS-36](https://airqoteam.atlassian.net/browse/PLATOPS-36?atlOrigin=eyJpIjoiNjE3OGU3ODExY2ViNDJlMTk1ZDRmZjI4ZDg3MWQ3Y2MiLCJwIjoiaiJ9)

### CODE REVIEW

**Review by 123MwanjeMike — COMMENTED** [review]
Guiding comments

**Review by Baalmart — APPROVED** [review]
Thanks @123MwanjeMike for these works.
I had expected fewer files because of Helm but I guess I will appreciate more as we move forward.

Thanks for the review comments too!

**Comment by 123MwanjeMike** [comment]
Yes @Baalmart 
Each Helm Chart has about 10 files and the initial total changed files were up to 59. I had to delete most of the auto generated files which weren’t using yet(like the tests and carts) to bring down the files to 45.

**Comment by Baalmart** [comment]
> Yes @Baalmart Each Helm Chart had about 10 files and the initial total changed files were up to 59. I had to delete most of the auto generated files which weren’t using yet(like the tests and carts) to bring down the files to **45**.
> 
> Also note that changes in the **8** k8s manifests were formatting changes by the linter in the pre-commit hook

Alright @123MwanjeMike , thanks for this.

**Pull request merged**
