### PR TITLE
Ft Homepage Tab View

### PR DESCRIPTION
**Pull request by FaithDaka**
#### Summary of Changes (What does this PR do?)
- Features CSS refactoring of the homepage sections for tablet size view ports and some QA action points.

#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [x] I consider this code done
- [x] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* Fetch and checkout _ft-qa-changes_ and resize the homepage to a tablet view.

#### What are the relevant tickets?
- [WEB-293]

#### Screenshots
Screenshot from 2022-07-27 11-23-06
Screenshot from 2022-07-27 11-23-13
Screenshot from 2022-07-27 11-23-21
Screenshot from 2022-07-27 11-23-29
Screenshot from 2022-07-27 11-23-37

[WEB-293]: https://airqoteam.atlassian.net/browse/WEB-293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by 123MwanjeMike — COMMENTED** [review]
Thanks @FaithDaka 
Although, there are changes in `netmanager/package-lock.json`without any corresponding changes in `netmanager/package.json`. It is related to something @Codebmk was working on but I feel we might want to undo them to avoid problematic changes to netmanager

**Review by 123MwanjeMike — APPROVED** [review]

**Comment by FaithDaka** [comment]
Was unable to remove the _package-lock.json_ file from the index without deleting it (almost deleted the remote branch).
The  _rm --cached_  command deleted the file remotely, so is that okay? @ja-odur

**Review by Baalmart — CHANGES_REQUESTED** [review]
Thanks @FaithDaka 

Based on the scope of this PR, I am just concerned about the "new changes" for netmanager's `package-lock.json` file. Won't it bring package related problems/issues to the Platform product?

**Comment by FaithDaka** [comment]
The changes were from testing the data export PR. @Baalmart 
So should this branch be deleted? Because I reverted the file to what it was before committing the data export changes.

**Review by Baalmart — CHANGES_REQUESTED** [review]
Thanks @FaithDaka 
Please review that changed package.lock.json file.
Ideally, we should not be seeing it among your changed files.

If the worst comes to the worst, you could just go manual to address this issue.

**Review by Codebmk — APPROVED** [review]
Tablet for the home page is looking great. Thanks.

**Review by Baalmart — CHANGES_REQUESTED** [review]
If all the recommended approaches of addressing the issue with the changed file fail, you might want to create a new branch from staging and start afresh. @FaithDaka @123MwanjeMike 

@123MwanjeMike could assist in finding better approaches.

Thanks for this!

**Comment by FaithDaka** [comment]
@Baalmart Tried different approaches with @123MwanjeMike last evening and none completely remove the file from the index without deleting it from this remote branch. Redoing this work is not feasible for this sprint.

**Pull request closed without merging**
