### PR TITLE
[Calibrate] Integrate Calibrate tool API

### PR DESCRIPTION
**Pull request by ja-odur**
#### Summary of Changes (What does this PR do?)
- Integrate backend api

#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [x] I consider this code done
- [x] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* Fetch and checkout to this branch locally
* Creates a `.env` file in the root directory. Contents of the `.env` file
```
REACT_APP_BASE_URL=http://staging-platform.airqo.net/api/v1/
REACT_APP_BASE_CALIBRATE_URL=
NODE_PATH=src/
PORT=5000
```
* Install requirements `npm install`
* Start netmanager staging application `npm run stage`
* Confirm the summary of changes listed above

#### What are the relevant tickets?
- [PLAT-1115](https://airqoteam.atlassian.net/browse/PLAT-1115)

#### Screenshots (optional)

### CODE REVIEW

**Review by 123MwanjeMike — APPROVED** [review]
LGTM

**Review by Priscilla-AL — COMMENTED** [review]
image


Maybe someone else should try

**Comment by sserurich** [comment]
> image
> 
> Maybe someone else should try

@Priscilla-AL , I had the same issue, however I resolved it by updating to the latest version of nodejs (v16).. If it doesn't automatically go away, consider checking [out this](https://stackoverflow.com/questions/69554485/eslint-error-must-use-import-to-load-es-module)

**Comment by Priscilla-AL** [comment]
> > image
> > Maybe someone else should try
> 
> @Priscilla-AL , I had the same issue, however I resolved it by updating to the latest version of nodejs (v16).. If it doesn't automatically go away, consider checking [out this](https://stackoverflow.com/questions/69554485/eslint-error-must-use-import-to-load-es-module)

Thanks, let me try that. But is everything else okay

**Review by danielogen — CHANGES_REQUESTED** [review]
Screen Shot 2022-05-10 at 11 05 48 AM

I think the backend URLs in frontend need to be updated following the recently merged calibration PR.

**Comment by Priscilla-AL** [comment]
> Screen Shot 2022-05-10 at 11 05 48 AM
> 
> I think the backend URLs in frontend need to be updated following the recently merged calibration PR.

Done!

**Review by danielogen — CHANGES_REQUESTED** [review]
Screen Shot 2022-05-10 at 12 56 17 PM

Looks like the app is stuck on loading

**Review by danielogen — APPROVED** [review]
LGTM

**Review by 123MwanjeMike — APPROVED** [review]
LGTM

**Comment by Priscilla-AL** [comment]
> This works well now, but when I try to calibrate and include reference monitor data (scenario 2) and put in pm2.5 or pm10, always get pm10 calibrated values. image

Must be a frontend issue cause when I test from the API it doesn't do that. Let me check out the code

**Pull request merged**
