### PR TITLE
[Netmanager] fix add image functionality

### PR DESCRIPTION
**Pull request by Codebmk**
#### Tasks
- Fix the image upload functionality
- upload and delete functionality for the images works just fine for any device selected.

#### Issues faced when working on this issue
- During the testing, I realized that the upload function was creating duplicate images, but that has been resolved.
- Finding the right Cloudinary preset value to use.

#### Status of maturity 
- [x] I've tested this locally and it works.

#### Notice
- Also when you try this out you'll notice that some images are broken in the giraffe device photos, this is because of the duplicate files that I deleted during testing but am sure they can be cleared from the database.

#### Screenshots
image

image

image

### CODE REVIEW

**Review by Baalmart — COMMENTED** [review]
Hi @Codebmk  , thanks! This is brilliant!

I have some quick feedback. Still testing though... 
See attached screenshot.
Screenshot 2023-02-15 at 15 34 48

**Review by 123MwanjeMike — COMMENTED** [review]
Hi @Codebmk 
I am getting the  same issue as @Baalmart 
image

**Comment by Baalmart** [comment]
> Hi @Codebmk 
> 
> When I try to delete the photo, I get this error
> 
> image
> 
> 
> 
> 

Hi @123MwanjeMike I am also seeing more details error messages in the notifs channel for device registry.
image

**Comment by Baalmart** [comment]
@Codebmk , it could be nice if we got this PR out of the way soon. Thanks!

**Comment by Baalmart** [comment]
Hi @Codebmk , please update the status (label) of this PR accordingly. And change it to DRAFT mode if that is more appropriate. Thanks!

**Review by Baalmart — APPROVED** [review]
LGTM, thanks @OchiengPaul442

**Pull request merged**
