### PR TITLE
[Analytics] Added settings page

### PR DESCRIPTION
**Pull request by CalebKatwigye**
#### Summary of Changes (What does this PR do?)
- Created a folder under pages and added files; profiledetails.jsx, and components; circularprogressindicator.jsx and togglebutton.jsx
- Under the pofiledetails.jsx page, there are two tabs that display content namely; profile details and email settings tab
- There are a series of text inputs, buttons and divider lines on both tab displays.
- The component circularprogressindicator.jsx works for only the 3 toggle buttons on the email settings tab and it contains a funstion that counts the number of buttons toggled and displays that number while showing radial progress in a blue color.

#### Status of maturity (all need to be checked before merging):

- [x] I've tested this locally
- [x] I consider this code done
- [x] This change ready to hit production in its current state
- [x] The title of the PR states what changed and the related issues number (used for the release note).
- [x] I've included issue number in the "Closes #ISSUE-NUMBER" part of the "[What are the relevant tickets?](#what-are-the-relevant-tickets)" section to [link the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [x] I've updated corresponding documentation for the changes in this PR.
- [x] I have written unit and/or e2e tests for my change(s).

#### How should this be manually tested?

- Verify that the components render without error by running "npm run dev".
- Interact with the text input fields by typing "Sample Text" and observe correct behavior.
- Click the buttons or hover over them to ensure that the cursor turns to pointer, among other expected actions.
- Check the styling, layout, and responsiveness of the components by adjusting the window size

#### What are the relevant tickets?

- #1375
- [AN-517](https://airqoteam.atlassian.net/browse/AN-517?atlOrigin=eyJpIjoiNmI3MTRjNGYwMDBmNDc3M2IxZmZhNDg2MzEyOWExOGYiLCJwIjoiaiJ9)

#### Screenshots (optional)
Screenshot from 2023-08-14 14-46-21
Screenshot from 2023-08-14 14-46-38
Screenshot from 2023-08-14 14-46-07
Screenshot from 2023-08-14 14-46-28

[AN-517]: https://airqoteam.atlassian.net/browse/AN-517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by CalebKatwigye** [comment]
This PR  is ready for review.

**Review by Baalmart — CHANGES_REQUESTED** [review]
Thanks @CalebKatwigye  for the amazing work!

1. I am just curious about the approach we are taking at the moment when it comes to the implementation of the analytics redesign.
2. I thought that we are no longer implementing "non functional" pages? Do we have the backends for the implemented screens in this PR? Since the collocation tool is already under usage, we do not want to confuse users with "dummy" pages that are not functional since it is a frustrating experience.

I am keen to hear about the strategy we are following at the moment so that I can align accordingly. cc: @Codebmk @PaulZana

**Comment by CalebKatwigye** [comment]
> Thanks @CalebKatwigye for the amazing work!
> 
> 1. I am just curious about the approach we are taking at the moment when it comes to the implementation of the analytics redesign.
> 2. I thought that we are no longer implementing "non functional" pages? Do we have the backends for the implemented screens in this PR? Since the collocation tool is already under usage, we do not want to confuse users with "dummy" pages that are not functional since it is a frustrating experience.
> 
> I am keen to hear about the strategy we are following at the moment so that I can align accordingly. cc: @Codebmk @PaulZana

Thank you @Baalmart for the concerns raised. I am currently unsure of the strategy being followed but the page is not connected to backend and my instructions from @Codebmk and @PaulZana  were to simply implement the UI design as per the Figma file. My guess is that backend for the page would be implemented shortly after that.

**Comment by Baalmart** [comment]
> > Thanks @CalebKatwigye for the amazing work!
> > 
> > 1. I am just curious about the approach we are taking at the moment when it comes to the implementation of the analytics redesign.
> > 2. I thought that we are no longer implementing "non functional" pages? Do we have the backends for the implemented screens in this PR? Since the collocation tool is already under usage, we do not want to confuse users with "dummy" pages that are not functional since it is a frustrating experience.
> > 
> > I am keen to hear about the strategy we are following at the moment so that I can align accordingly. cc: @Codebmk @PaulZana
> 
> Thank you @Baalmart for the concerns raised. I am currently unsure of the strategy being followed but the page is not connected to backend and my instructions from @Codebmk and @PaulZana were to simply implement the UI design as per the Figma file. My guess is that backend for the page would be implemented shortly after that.

Thanks @CalebKatwigye , based on your notes, I  then suggest that:

1.  You change the label of this PR to `work in progress`. 
2. `Ready to review` should be when the backend functionality has also been integrated and working well within the system. We do not want to intentionally frustrate our existing collocation tool users with non functional pages as we already noticed from an earlier attempt of this current strategy.

**Comment by CalebKatwigye** [comment]
> > > Thanks @CalebKatwigye for the amazing work!
> > > 
> > > 1. I am just curious about the approach we are taking at the moment when it comes to the implementation of the analytics redesign.
> > > 2. I thought that we are no longer implementing "non functional" pages? Do we have the backends for the implemented screens in this PR? Since the collocation tool is already under usage, we do not want to confuse users with "dummy" pages that are not functional since it is a frustrating experience.
> > > 
> > > I am keen to hear about the strategy we are following at the moment so that I can align accordingly. cc: @Codebmk @PaulZana
> > 
> > 
> > Thank you @Baalmart for the concerns raised. I am currently unsure of the strategy being followed but the page is not connected to backend and my instructions from @Codebmk and @PaulZana were to simply implement the UI design as per the Figma file. My guess is that backend for the page would be implemented shortly after that.
> 
> Thanks @CalebKatwigye , based on your notes, I then suggest that:
> 
> 1. You change the label of this PR to `work in progress`.
> 2. `Ready to review` should be when the backend functionality has also been integrated and working well within the system. We do not want to intentionally frustrate our existing collocation tool users with non functional pages as we already noticed from an earlier attempt of this current strategy.

@Baalmart Certainly.

**Pull request closed without merging**
