### PR TITLE
[NetManager] Fix node memory issue

### PR DESCRIPTION
**Pull request by ja-odur**
#### Summary of Changes (What does this PR do?)
Fixes this [issue](https://github.com/airqo-platform/AirQo-frontend/issues/133) by;
- Increasing node memory limit
- Adding options to build without generating source maps.

#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [x] I consider this code done
- [x] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* Pull and checkout to this [branch]() locally
* Install node requirements `npm install`
* Build the app with source maps `npm run build`
* Build the app without source maps `npm run SMD-build-mac` (on Mac OS) or `npm run SMD-build-pc` (on windows paltform)
* Both build must be successful.

#### What are the relevant tickets?
- [PLAT-227](https://airqoteam.atlassian.net/browse/PLAT-227)

#### Screenshots (optional)

> Please add run command for Windows too.

### CODE REVIEW

**Review by lilly-muyama — APPROVED** [review]
LGTM

**Review by sserurich — APPROVED** [review]
Build succeeds, and can serve the application from the build folder,  which was the objective of PR
the issue I encountered was that npm build  takes alot of time  to finish, and couldn't go beyond the login page, but I was informed fix is in another PR.

**Comment by danielogen** [comment]
So far so good. I will test it using a node docker image and provide feedback accordingly.

**Review by Baalmart — APPROVED** [review]
Works well.

**Pull request merged**
