### PR TITLE
[WEBSITE] Clean-air Network (Partners page implementation)

### PR DESCRIPTION
**Pull request by OchiengPaul442**
#### Summary of Changes (What does this PR do?)

- Partners view implementation 
- Included SEO on the clean air pages 

#### Status of maturity (all need to be checked before merging):

- [x] I've tested this locally
- [x] I consider this code done
- [x] This change ready to hit production in its current state

#### Screenshots (optional)
image
image

### CODE REVIEW

**Comment by Baalmart** [comment]
@OchiengPaul442 , we have merge conflicts on this PR.

**Review by Baalmart — COMMENTED** [review]
Thanks @OchiengPaul442 , this looks good to me.
Just one small comment as seen (described) in the attached screenshot.
Screenshot 2023-11-01 at 23 33 00

**Comment by OchiengPaul442** [comment]
Can't remove it @Baalmart, I will just increase the size for better visibility. 
Thanks

**Comment by FaithDaka** [comment]
Ready for merge @Baalmart

**Comment by Baalmart** [comment]
> Ready for merge @Baalmart

thanks @FaithDaka for this alert.

**Pull request merged**
