### PR TITLE
uptime analysis graph, offline devices & online/offline status piechart

### PR DESCRIPTION
**Pull request by sserurich**
**What does this PR do?**
 Displays implementation of uptime analysis graph, offline devices table & online/offline status piechart
Which JIRA card(s)?

How do I test out this PR?
Git clone this repo cd AirQo-fronted/locate, 
-  git fetch branch  **ft-device-online-offline-status-piechart**  
- run npm install to get all the necessary dependencies. 
-After, run npm run local to view the changes. 
- Remember to have the backend service running as well (https://github.com/airqo-platform/AirQo-api/pull/80). 
**Which endpoints should be /are ready for testing?**
There are no endpoints for testing this PR.
image

### CODE REVIEW

**Comment by sserurich** [comment]
> Which backend service should be running? @sserurich

@Baalmart , utelise this backend service in this [PR](https://github.com/airqo-platform/AirQo-api/pull/80)

**Comment by Baalmart** [comment]
> > Which backend service should be running? @sserurich
> 
> @Baalmart , utelise this backend service in this [PR](https://github.com/airqo-platform/AirQo-api/pull/80)

Cool

**Comment by sserurich** [comment]
> I'm curious about some of the files changed that have no bearing here e.g. LocateForm ,LocateSave etc. Also that Main.js from analytics shouldn't be there and it seems to have some problematic lines e.g. 65, 72. I hope it wasn't merged into Master

@lilly-muyama , main.js has been resolved.. merge conflicts addressed by accepting changes from master.
- about LocateForm,LocateSave will first consult before removing them, don't remember adding anything like that. if it's okay to remove them @lilly-muyama @danielogen , feel free in to get in touch. 

> We need:
> 
> * To use constants for all URls in scripts.
> * To fix the merge conflicts with master

- merge conflicts have been fixed 
- URIs for this particular product are using constants as required.

**Comment by sserurich** [comment]
> Let there only be 2 leader boards showing best and worst performing devices (preferably past 28 days) taking into consideration only devices that are on the network (i.e. have a location id and aren't retired). Thank you.
These have been addressed in the latest commits.

**Pull request merged**
