### PR TITLE
[Analytics] Update Profile and checklist bug fixes

### PR DESCRIPTION
**Pull request by OchiengPaul442**
#### Summary of Changes (What does this PR do?)

- Worked on the user checklists 
- Worked on the Update Profile issues
- Layout UI Fix

#### Status of maturity (all need to be checked before merging):

- [x] I've tested this locally
- [x] I consider this code done
- [x] This change is ready to hit production in its current state

#### Screenshots (optional)
image

### CODE REVIEW

**Review by Codebmk — APPROVED** [review]
LGTM
image

**Review by Codebmk — CHANGES_REQUESTED** [review]
Oops some stuff's broken @OchiengPaul442 
image

image

**Comment by OchiengPaul442** [comment]
Thanks @Codebmk ,
Will resolve these.

**Review by Codebmk — APPROVED** [review]
All resolved thanks

**Pull request merged**
