### PR TITLE
Enabling Translations for KYA and Quiz

### PR DESCRIPTION
**Pull request by BenjaminSsempala**
#### Summary of Changes (What does this PR do?)

- Translation for KYA and Quiz.

#### Status of maturity (all need to be checked before merging):

- [ ] I've tested this locally
- [ ] I consider this code done
- [ ] This change ready to hit production in its current state
- [ ] The title of the PR states what changed and the related issues number (used for the release note).
- [ ] I've included issue number in the "Closes #ISSUE-NUMBER" part of the "[What are the relevant tickets?](#what-are-the-relevant-tickets)" section to [link the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [ ] I've updated corresponding documentation for the changes in this PR.
- [ ] I have written unit and/or e2e tests for my change(s).

#### How should this be manually tested?

- Please include the steps to be done inorder to setup and test this PR.

#### What are the relevant tickets?

- Closes #<enter issue number here>
- [Jira_card_number]() (If exists)

### CODE REVIEW

**Comment by katendejericho5** [comment]
@BenjaminSsempala  for some reason the translation of the health tips and KYA is not working perhaps @Mnoble-19 could run this PR so that we're sure it's not device specific

**Review by Baalmart — COMMENTED** [review]
Thanks @BenjaminSsempala for this PR, much appreciated! :)

- I guess there is some feedback from Jericho which still needs further review.
- Also, the PR reduces the test coverage by a certain percentage. Care to share some thoughts on this?

**Comment by BenjaminSsempala** [comment]
> @BenjaminSsempala for some reason the translation of the health tips and KYA is not working perhaps @Mnoble-19 could run this PR so that we're sure it's not device specific 

@katendejericho5 This PR doesn't target health tips.

**Comment by Baalmart** [comment]
@BenjaminSsempala , you have some merge conflicts to resolve here

**Comment by BenjaminSsempala** [comment]
> @BenjaminSsempala , you have some merge conflicts to resolve here

@Baalmart I've resolved this.

**Pull request merged**
