### PR TITLE
[Netmanager] User feedback

### PR DESCRIPTION
**Pull request by FaithDaka**
#### Summary of Changes (What does this PR do?)

- Clean up account details input overlap
- User tables breadcrumb component
- Create sites and devices without setting the network
- Store device overview details in redux state
- Initial refactor of device details charts
- Refactor of device details table to show essential details.
- Refactor device overview layout

#### Status of maturity (all need to be checked before merging):

- [x] I've tested this locally
- [x] I consider this code done
- [x] This change ready to hit production in its current state
- [x] The title of the PR states what changed and the related issues number (used for the release note).
- [x] I've included issue number in the "Closes #ISSUE-NUMBER" part of the "[What are the relevant tickets?](#what-are-the-relevant-tickets)" section to [link the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

#### How should this be manually tested?

- Using the deploy preview, visit device details to see changes

#### What are the relevant tickets?

- [AN-425]
- [AN-424]
- [AN-433]

#### Screenshots
image

image

image

image

[AN-425]: https://airqoteam.atlassian.net/browse/AN-425?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by Baalmart — COMMENTED** [review]
Thanks @FaithDaka for this.
A quick blocker as I tried to check out the deploy preview link, please check out **attached screenshot**. I just get a white screeen. Could it be that it requires a backend fix?
Screenshot 2023-06-06 at 14 40 00

**Comment by FaithDaka** [comment]
There was a global variable that couldn't be found before initilisation. That has been updated @Baalmart

**Comment by Baalmart** [comment]
> here

Alright, thanks @FaithDaka , let me test out again

**Review by Baalmart — APPROVED** [review]
Thanks @FaithDaka , what a brilliant PR! God bless you!

**Pull request merged**
