### PR TITLE
FT: update top cards on netmanager

### PR DESCRIPTION
**Pull request by danielogen**
**What does this PR do?**
- Add a card for battery-powered devices
- Add a card for devices overdue maintenances
- Update code based on feedback from PO and SM guide

**What JIRA task is related to this PR?**
JIRA task is [here](https://airqoteam.atlassian.net/browse/NET-78)
**How do I test out this PR?**
Git clone this repo `cd AirQo-frontend/locate`. Then run `npm install` to get all the necessary dependencies. Afterwards, run `npm run local` to test out the various features of the locate platform. Also, make sure `device-monitoring` API is running simultaneously.
**Which endpoints are ready for testing?**
None

### CODE REVIEW

**Comment by lilly-muyama** [comment]
Which branch should we be running in the backend @danielogen ?

**Comment by danielogen** [comment]
> Which branch should we be running in the backend @danielogen ?

Kindly look at this PR https://github.com/airqo-platform/AirQo-api/pull/106

**Comment by danielogen** [comment]
> @danielogen , thanks.
> I have run the latest master in device-monitoring using: `flask run`.
> I have also run: the frontend repo using: `npm run local` in ft-update-top-cards.
> I get the following output:
> image
> 
> Could I be missing something?

Hi @Baalmart, the updated backend service is available [here](https://github.com/airqo-platform/AirQo-api/pull/106)

**Comment by sserurich** [comment]
> looks good, the cards were added.

image

**Pull request merged**
