### PR TITLE
[Netmanager] Responsiveness of the Average Chart Modal header

### PR DESCRIPTION
**Pull request by danielmarv**
#### Summary of Changes (What does this PR do?)

- I have made the Average Chart Modal header to be responsive on all devices
- Before it was conflicting on small devices.

#### Status of maturity (all need to be checked before merging):

- [x] I've tested this locally
- [x] I consider this code done
- [x] This change ready to hit production in its current state
#### What are the relevant tickets?

- [AN-498](https://airqoteam.atlassian.net/browse/AN-498)

#### Before
prob

#### After
prob1

[AN-498]: https://airqoteam.atlassian.net/browse/AN-498?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by Codebmk** [comment]
THanks. This chart hasn't been worked on btw. Maybe adding it to this PR?? @danielmarv 
image

**Comment by danielmarv** [comment]
no not on this branch

**Review by Codebmk — CHANGES_REQUESTED** [review]
Requires some padding on the left and right
image

**Review by Codebmk — APPROVED** [review]
LGTM @danielmarv

**Pull request merged**
