### PR TITLE
[Netmanager] Predict and display air quality for a given location

### PR DESCRIPTION
**Pull request by Codebmk**
#### Summary of Changes (What does this PR do?)

- Adds a search bar on top navigation bar
- Uses autocomplete to suggest locations similar to the search input
- Uses the metadata api to display the location administrative levels
- Uses the predict api to return the air quality reading

#### Status of maturity (all need to be checked before merging):

- [x] I've tested this locally
- [x] I consider this code done
- [x] This change ready to hit production in its current state

#### How should this be manually tested?

- On the top bar, click the search icon on the top bar which will open up a dialog where you can type a location name and will be shown its corresponding air quality. For now it works for Kira airqloud locations
Or 
- cd into netmanager
- npm install
- npm run stage
- on the home page, click the search bar on the top navigation bar and search for a location within kira airqloud

#### What are the relevant tickets?

- Closes #<enter issue number here>
- [AN_414](https://airqoteam.atlassian.net/browse/AN-414)

#### Screenshots (optional)
image
image
image

### CODE REVIEW

**Review by Baalmart — COMMENTED** [review]
@Codebmk , thanks!
After login, I am not able to see this feature mentioned in the PR. Even the screenshots indicate that it is on the dashboard page but I still see nothing related to the PR.

Please clarify with more notes or clearer screenshots.

Thanks again!

https://ft-predict-search-netmanager-preview-w7kzhvlewq-ew.a.run.app/dashboard

Screenshot 2023-05-27 at 09 21 05

**Review by Baalmart — COMMENTED** [review]
@Codebmk , thanks!
After login, I am not able to see this feature mentioned in the PR. Even the screenshots indicate that it is on the dashboard page but I still see nothing related to the PR.

Please clarify with more notes or clearer screenshots.

Thanks again!

https://ft-predict-search-netmanager-preview-w7kzhvlewq-ew.a.run.app/dashboard

Screenshot 2023-05-27 at 09 21 05

**Comment by Codebmk** [comment]
> @Codebmk , thanks! After login, I am not able to see this feature mentioned in the PR. Even the screenshots indicate that it is on the dashboard page but I still see nothing related to the PR.
> 
> Please clarify with more notes or clearer screenshots.
> 
> Thanks again!


The search bar is right there in your screenshot on the top navigation menu(right hand side)

**Comment by Codebmk** [comment]
Also, the pr requires that you set a new env as I shared on slack `REACT_APP_GOOGLE_MAPS_KEY` and the key can be found in gcp under the google javascript maps api

https://airqo.slack.com/archives/C03G85EEJ1J/p1684954397959579

**Comment by Baalmart** [comment]
> Also, the pr won't work as expected as it is missing an env as I shared on slack `REACT_APP_GOOGLE_MAPS_KEY` and the key can be found in gcp under the google javascript maps api
> 
> https://airqo.slack.com/archives/C03G85EEJ1J/p1684954397959579

thanks @Codebmk , I think I added this ENV, will crosscheck. We might want to trigger another preview to effect that ENV? @123MwanjeMike

**Comment by FaithDaka** [comment]
Searched for Kira Town as shown in the screenshot but got an error instead:
Screenshot (136)

Otherwise the frontend design LGTM!

**Comment by NoahNsimbe** [comment]
Thanks @FaithDaka. It's most likely to be related to `REACT_APP_GOOGLE_MAPS_KEY` api key. cc @Baalmart

**Comment by Baalmart** [comment]
Hi @NoahNsimbe , this key was already added to all secrets. Perhaps just make any new commit to "trigger" the key updates. @FaithDaka

**Comment by Codebmk** [comment]
@Baalmart you might need to generate a new api key ie delete the existing google javascript map keys, create new ones, enable them and add those. During development, I was unable to use the ones Noah shared with me so I used one from my console.

image

**Comment by Baalmart** [comment]
> @Baalmart you might need to generate a new api key ie delete the existing google javascript map keys, create new ones, enable them and add those. During development, I was unable to use the ones Noah shared with me so I used one from my console.
> 
> image

Alright @Codebmk , thanks for that clarification

**Comment by Baalmart** [comment]
> REACT_APP_GOOGLE_MAPS_KEY

Hi @Codebmk , this new ENV has been added to the cloud code, as requested.
Please test out accordingly. I am not sure about what needs to be done? Push a new commit? 
cc: @123MwanjeMike

**Review by Baalmart — APPROVED** [review]
LGTM, thanks @Codebmk

**Pull request merged**
