### PR TITLE
[Website] Cameroon airqloud

### PR DESCRIPTION
**Pull request by FaithDaka**
#### Summary of Changes (What does this PR do?)
- Features new Cameroon airqloud for footer modal

#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [x] I consider this code done
- [x] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* View modal in deploy preview

#### What are the relevant tickets?
- [WEB-335]

[WEB-335]: https://airqoteam.atlassian.net/browse/WEB-335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by wabinyai — APPROVED** [review]
Looks good. Thanks for the addition

**Review by wabinyai — COMMENTED** [review]
Looks good

**Review by wabinyai — APPROVED** [review]

**Review by 123MwanjeMike — APPROVED** [review]
LGTM

image

**Review by Baalmart — APPROVED** [review]
LGTM

**Pull request merged**
