### PR TITLE
[NetManager] update analytics url

### PR DESCRIPTION
**Pull request by ja-odur**
#### Summary of Changes (What does this PR do?)
- Update analytics url to conform to API Gateway standards

#### Is this change ready to hit production in its current state?
- [ ] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [ ] I consider this code done
- [ ] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* Please include the steps to be done inorder to setup and test this PR.

#### What are the relevant tickets?
- [PLAT-499](https://airqoteam.atlassian.net/browse/PLAT-499)

#### Screenshots (optional)

### CODE REVIEW

**Review by lilly-muyama — APPROVED** [review]
LGTM

**Review by NoahNsimbe — APPROVED** [review]
LGTM

**Review by danielogen — APPROVED** [review]
LGTM

**Review by danielogen — COMMENTED** [review]
Great work @ja-odur . I'm going to merge it to staging since the corresponding backend is already merged.

**Pull request merged**
