### PR TITLE
[Website] Ft Privacy Policy

### PR DESCRIPTION
**Pull request by FaithDaka**
#### Summary of Changes (What does this PR do?)

- Features privacy policy

#### Status of maturity (all need to be checked before merging):

- [x] I've tested this locally
- [x] I consider this code done
- [x] This change ready to hit production in its current state

#### How should this be manually tested?

- View privacy policy through deploy preview

#### What are the relevant tickets?

- [WEB-234]

[WEB-234]: https://airqoteam.atlassian.net/browse/WEB-234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by 123MwanjeMike — CHANGES_REQUESTED** [review]
Great stuff @FaithDaka 
I suspect that the terms of use are for all our products and not just the platform.
Can we have either all of them included or the product changed from platform to the website?

image

Also note that we have the platform T&C's on the [docs site](https://staging-docs.airqo.net/#/platform/terms_and_conditions)

cc @Baalmart

**Comment by FaithDaka** [comment]
@123MwanjeMike That's a conversation that has to include Priscah as the content lead. I personally can't review the legalities represented

**Comment by 123MwanjeMike** [comment]
> @123MwanjeMike That's a conversation that has to include Priscah as the content lead. I personally can't review the legalities represented

Thanks @FaithDaka
@Baalmart, any advice on a way forward?

**Comment by Baalmart** [comment]
> > @123MwanjeMike That's a conversation that has to include Priscah as the content lead. I personally can't review the legalities represented
> 
> Perhaps @Baalmart can advice on a way forward. Otherwise, great work @FaithDaka .

Hi @123MwanjeMike and @FaithDaka  , Content discussions can be left for Priscah. For this PR, we could just discuss the technical aspects like the ones I am about to share.....

1. How easy will be it for us to make changes/adjustments to this privacy policy. Would it require a PR for any content changes? 
2. How does this align with our "online documentations product" which @123MwanjeMike is leading?

**Comment by FaithDaka** [comment]
@Baalmart 
1. Yes it would require a PR for changes
2. I don't know

**Review by 123MwanjeMike — APPROVED** [review]
Thanks @FaithDaka & @Baalmart 
LGTM

**Comment by Baalmart** [comment]
> Thanks @FaithDaka & @Baalmart LGTM

Alright @FaithDaka ....thanks for the clarification.
We shall revisit this in due course. 
Our ideal situation is to make most of our website content dynamic.

**Review by Baalmart — APPROVED** [review]
LGTM

**Pull request merged**
