### PR TITLE
[Netmanager]Making the Dashboard charts to look better

### PR DESCRIPTION
**Pull request by danielmarv**
#### Summary of Changes

- i have provided a limit on the number of the locations to be portrayed on the graph.
- Reduce on the overcrowdness of the Dashboard Charts.
- Created new dialogs to show the details and stand alone charts for each and every location in an airqloud.

#### Status of maturity 

- [x] I've tested this locally
- [x] I consider this code done
- [x] This change ready to hit production in its current state

#### How should this be manually tested?

- I have created buttons that gives the user options on both the exceedance and Average charts  

#### What are the relevant tickets?

- [AN-462](https://airqoteam.atlassian.net/browse/AN-462)

#### Screenshots (optional)

- I limited the number of bars on the charts to 10 bars

[AN-462]: https://airqoteam.atlassian.net/browse/AN-462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
task5

- I used a button to dsplay all location stats on the dialog

task3
task4
task1

### CODE REVIEW

**Review by Codebmk — COMMENTED** [review]
Yoo hope we are still working on this task @danielmarv . The selected chart seems to disappear in the background.

image

**Comment by danielmarv** [comment]
@Codebmk it is a still work in progress

**Comment by Codebmk** [comment]
I have left several feedback in your DM @danielmarv . Let's aim to get this done before demo tomorrow. Awesome progress

**Comment by Codebmk** [comment]
1. Update the font size of the title to be bigger
2. Remove full stop from end of the text "0 Locations." to "0 locations"
3. Adjust font size of the air quality status in between the location and value to make it more visible and make it centered on the yaxis
image

How does the bar chart look like when you adjust the size of the bars to be a little bigger?
image

**Review by NoahNsimbe — COMMENTED** [review]
Thanks @danielmarv. The yellow colour of UFSG is not visible.

**Review by Codebmk — APPROVED** [review]
Woah!! This is the PR of the century. Thanks man, @danielmarv!
image

We can iterate on the next PR.

**Review by Baalmart — APPROVED** [review]
Thanks @danielmarv

**Pull request merged**
