### PR TITLE
[WEB] API page implementation

### PR DESCRIPTION
**Pull request by OchiengPaul442**
#### Summary of Changes (What does this PR do?)

- Implemented the API page

#### Status of maturity (all need to be checked before merging):

- [x] I've tested this locally
- [x] I consider this code done
- [x] This change ready to hit production in its current state

- [Jira_card_number]() [(If exists)](https://airqoteam.atlassian.net/browse/WEB-379)

#### Screenshots (optional)
image
image

### CODE REVIEW

**Comment by FaithDaka** [comment]
Great work @OchiengPaul442 
Ready for review and merge @Baalmart Feel free to read through the content

**Review by Baalmart — APPROVED** [review]
Thanks @OchiengPaul442

**Comment by Baalmart** [comment]
I will merge after PR gets at least one more other approval. cc:  @FaithDaka

**Comment by FaithDaka** [comment]
Great work @OchiengPaul442 I had to trigger some changes I'd made that weren't showing up.

@Baalmart It would be great if you read the improvised content to if it makes sense, then we can merge

**Review by FaithDaka — APPROVED** [review]

**Comment by Baalmart** [comment]
> here

thanks @FaithDaka , we can always review the content.
Personally, I am against the deliberate mention of the word "developers" as if the API only helps developers.

Businesses like Banks, NBS and etc can take advantage of our API....so it is NOT a "developer thing" per say.
Example tweet where MTN was promoting their APOI without mention the word developers at all! https://twitter.com/mtnug/status/1674404113906298881?s=20

The more we promote API as a "developer thing", the more it stays that way! :)

**Pull request merged**
