### PR TITLE
[Netmanager] Soft add device support

### PR DESCRIPTION
**Pull request by Codebmk**
#### Summary of Changes (What does this PR do?)

- Enabled soft add devices
- Removed optional fields in device creation form
- Added optional fields to Edit Device form
 
#### Status of maturity (all need to be checked before merging):

- [ ] I've tested this locally
- [ ] I consider this code done
- [ ] This change ready to hit production in its current state
- [ ] The title of the PR states what changed and the related issues number (used for the release note).
- [ ] I've included issue number in the "Closes #ISSUE-NUMBER" part of the "[What are the relevant tickets?](#what-are-the-relevant-tickets)" section to [link the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [ ] I've updated corresponding documentation for the changes in this PR.
- [ ] I have written unit and/or e2e tests for my change(s).

#### How should this be manually tested?

- Please include the steps to be done inorder to setup and test this PR.

#### Screenshots (optional)
Screenshot from 2023-02-06 15-22-37
Screenshot from 2023-02-06 15-22-21
Screenshot from 2023-02-06 15-22-03

### CODE REVIEW

**Review by Baalmart — COMMENTED** [review]
Thanks @Codebmk , this is amazing work!
We have some merge conflicts that need to be resolved.

**Comment by Codebmk** [comment]
@Baalmart I have resolved the merge conflicts. However, deploy preview is not working. @123MwanjeMike

**Comment by Baalmart** [comment]
@123MwanjeMike please assist. Thanks!

**Comment by 123MwanjeMike** [comment]
> @123MwanjeMike please assist. Thanks!

Hi @Baalmart 
This branch is outdated and needs to pull the latest changes from staging.
I’ve shared with @Codebmk

**Comment by Baalmart** [comment]
Hi @Codebmk I am still not able to see the deploy preview for this PR? @123MwanjeMike

**Review by 123MwanjeMike — APPROVED** [review]
Thanks @Codebmk 
LGTM

**Comment by 123MwanjeMike** [comment]
> Hi @Codebmk I am still not able to see the deploy preview for this PR? @123MwanjeMike

Hi @Baalmart, this issue has been resolved

**Pull request merged**
