### PR TITLE
[WEBSITE] Monitor Page

### PR DESCRIPTION
**Pull request by FaithDaka**
#### Summary of Changes (What does this PR do?)

- Design of monitor page (1/4 of products pages)
- Navigation through header
- Page assets

#### Status of maturity (all need to be checked before merging):

- [x] I've tested this locally
- [x] I consider this code done
- [x] This change ready to hit production in its current state
- [x] The title of the PR states what changed and the related issues number (used for the release note).

#### How should this be manually tested?

- Click _Products_ in homepage top bar nav to view its dropdown menu.
- Click Binos Monitor to view Monitor page.
- Change your browser window to check for responsiveness of components

#### What are the relevant tickets?

- [WEB-378]

#### Screenshots 
image

image

[WEB-378]: https://airqoteam.atlassian.net/browse/WEB-378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by Baalmart — COMMENTED** [review]
Thanks @FaithDaka , this is great!

I have left behind some feedback using screenshots. Awaiting your thoughts.
image
image

**Comment by FaithDaka** [comment]
Please view the Figma designs @Baalmart

**Comment by Baalmart** [comment]
> Please view the Figma designs @Baalmart That is the padding used in those sections.

Alright, thanks @FaithDaka

**Review by Baalmart — APPROVED** [review]
LGTM, thanks @FaithDaka

**Pull request merged**
