### PR TITLE
Added Analytics section

### PR DESCRIPTION
**Pull request by Codebmk**
#### Summary of Changes (What does this PR do?)
- Added analytics section(both mobile and web)

#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [x] I consider this code done
- [x] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### What are the relevant tickets?
- [WEB-105](https://airqoteam.atlassian.net/browse/WEB-105)

### CODE REVIEW

**Comment by Codebmk** [comment]
analytics mobile
analytics web
@ja-odur this PR is ready for review

**Review by 123MwanjeMike — COMMENTED** [review]
LGTM

**Review by 123MwanjeMike — APPROVED** [review]

**Comment by FaithDaka** [comment]
For consistency, I think you should use the arrow-right icon from the designs. It's part of the icons folder. @Codebmk 
As well as match the font-weight of the "Learn more" span.

**Comment by Codebmk** [comment]
> For consistency, I think you should use the arrow-right icon from the designs. It's part of the icons folder. @Codebmk As well as match the font-weight of the "Learn more" span.

@FaithDaka the font-weight matches(600) with that for figma

**Review by ja-odur — APPROVED** [review]
@Codebmk  This component seems to be larger than on the design. We will have to fix this in the next iteration of the homepage.

**Pull request merged**
