### PR TITLE
[Netmanager] User Management Features

### PR DESCRIPTION
**Pull request by Baalmart**
- What does this PR do?
Incorporates many components for user management into the Netmanager product - transfers them from "Analytics"
Same PR also updates the favicon of the product - as seen in the browser window.
It also disables the registration page - leaving the Login page as the only option.

- How to test out PR?
`cd netmanager`
`npm install`

> For MAC

`npm run dev-mac` for development environment
`npm run prod-mac` for production environment
`npm run stage-mac` for staging environment

> For Windows

`npm run dev-pc` for development environment
`npm run prod-pc` for production environment
`npm run stage-pc` for staging environment

- Any considerations?
When running in the **development environment**, please ensure that the **auth-service microservice** is running at the same time.
Otherwise, no need to do if you are running in the production environment.

### CODE REVIEW

**Review by danielogen — APPROVED** [review]
Looks great. Thank you. Some quick comment:
- Clicking `candidates` link throws an error
Screenshot 2020-09-04 at 09 37 47

**Comment by Baalmart** [comment]
> Looks great. Thank you. Some quick comment:
> 
> * Clicking `candidates` link throws an error
>   Screenshot 2020-09-04 at 09 37 47

let me just disable that item for now --- shall address later after demo. Sending through a new commit in a few...

**Review by Priscilla-AL — COMMENTED** [review]
No favicon icon on my side, the rest looks good though

**Comment by danielogen** [comment]
> No favicon on my browser, the rest looks good though

Maybe you can try to clear your browser cache. Mine worked perfectly

**Review by Priscilla-AL — APPROVED** [review]

**Pull request merged**
