### PR TITLE
Add "Edit on GitHub" feature on the AirQo Docs

### LINKED ISSUE #841: Add "Edit on GitHub" feature on the AirQo Docs
**Is your feature request related to a problem? Please describe.**
We want to empower the users of our docs to be able to catch and correct any quick fix issues they come across when using our docs.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by HassanBahati**
#### Summary of Changes (What does this PR do?)
- This pr addresses  #841

#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [x] I consider this code done
- [x] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* Pull changes from [this branch](https://github.com/HassanBahati/AirQo-frontend/tree/edit-on-github-feature)
* Build and Run the docs 

#### What are the relevant tickets?
- Closes #841

#### Screenshots (optional)
Screenshot from 2022-10-21 18-26-08
Screenshot from 2022-10-21 18-26-22

### CODE REVIEW

**Comment by HassanBahati** [comment]
@123MwanjeMike @Codebmk @Baalmart 
I need guidance on two concerns;
1. what is the appropriate expected font case for the Edit On GitHub Link on every page? **Uppercase or capitalized**? At the moment i have have it capitalized as **Edit On GitHub** versus **EDIT ON GITHUB**.
2. What should be the position of the Edit On GitHub link ? At the **Top of the page** or at the **Bottom of the Page** ? In this pr , i have placed both at the top and the bottom until you guide further.

this screenshot represents the Edit On GitHub button at the top of the page
Screenshot from 2022-10-21 18-26-08

this screenshot represents the Edit On GitHub button at the top of the page
Screenshot from 2022-10-21 18-26-22

**Comment by 123MwanjeMike** [comment]
Great progress @HassanBahati. To answer your questions:
1. The current font size used is fine. All Caps is a little alarming to use in this case.
2. I think we can keep the button at the top. That in away lets the users know before hand that they are empowered to correct mistakes they find along the way.

**Comment by HassanBahati** [comment]
> Great progress @HassanBahati. To answer the questions raised;
> 
>     1. The current font size used is fine. All Caps is a little alarming to use in this case.
> 
>     2. I think we can keep the button at the top. That in a way lets the users know before hand that they are empowered to correct mistakes they find along the way.

Alright @123MwanjeMike , i have maintained the edit link at top of page and removed it from bottom of the page

**Review by 123MwanjeMike — APPROVED** [review]
Great work @HassanBahati 
LGTM

**Review by Codebmk — APPROVED** [review]
LGTM @HassanBahati

**Review by Baalmart — APPROVED** [review]

**Pull request merged**
