### PR TITLE
[Website] Ft airquality section

### PR DESCRIPTION
**Pull request by FaithDaka**
#### Summary of Changes (What does this PR do?)
- Features airquality section, right below the partners section.

#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [x] I consider this code done
- [x] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* Fetch the 'ft-airquality-section' branch and run standalone script.

#### What are the relevant tickets?
- [WEB-211]

#### Screenshots
For African Cities
Screenshot from 2022-06-09 10-23-28

For Communities
Screenshot from 2022-06-09 10-23-36

Mobile-view
Screenshot from 2022-06-09 11-24-55

Screenshot from 2022-06-09 11-25-14

[WEB-211]: https://airqoteam.atlassian.net/browse/WEB-211?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by FaithDaka** [comment]
Two things to note:
1. The user flow for the tab switch ('For African Cities' and 'For Communities') hasn't been added yet, so I improvised just to show the change.
2. The mobile design hasn't been updated to match the new web view so I also improvised as well.

**Review by Codebmk — CHANGES_REQUESTED** [review]
Great work @FaithDaka . I notice some tiny differences in the border radius of the toggle buttons for mobile and the background color that wraps around them.

airqualit-section

Figma design
airqualit-section-figma

**Comment by FaithDaka** [comment]
The mobile view on figma has not been updated yet. That was from the old design. I want to ask him about that in the meeting this afternoon!

**Comment by Codebmk** [comment]
> The mobile view on figma has not been updated yet. That was from the old design. I want to ask him about that in the meeting this afternoon!

Alrighty

**Comment by FaithDaka** [comment]
New changes

Screenshot from 2022-06-10 16-59-08
Screenshot from 2022-06-10 16-59-21

**Pull request merged**
