### PR TITLE
[Netmanager] Sessions Timeout For user login

### PR DESCRIPTION
**Pull request by danielmarv**
#### Summary of Changes (What does this PR do?)

- i have triggered session timeout for the users when there is inactivity for 30 Minutes
- I have failed to include the tests because of some unmet dependencies in the staging of which am not the cause.

#### Status of maturity (all need to be checked before merging):

- [x] I've tested this locally
- [x] I consider this code done
- [x] This change ready to hit production in its current state

#### What are the relevant tickets?

- [Jira_card_number]()

### CODE REVIEW

**Review by Baalmart — COMMENTED** [review]
thanks @danielmarv for the amazing work!
I will test out and share feedback as soon as possible.

**Review by Baalmart — COMMENTED** [review]
As for the unit tests, they are now mandatory...so please resolve those "unmet" dependencies accordingly. @danielmarv

**Comment by danielmarv** [comment]
but as for the functionality is everything ok no any changes needed????

**Comment by Baalmart** [comment]
> here

@danielmarv 
I have just logged in, I am now waiting to be logged out.  
Will share feedback shortly

**Comment by danielmarv** [comment]
but it with out user activity so it is set to 30 minutes with out any activity 
if you do any activity on the platform it reset the timer

**Comment by danielmarv** [comment]
or i first reduce the duration to stop time wastage

**Comment by Baalmart** [comment]
Hi @danielmarv 
Not sure but I am still logged into the system after 30 mins elapsed. How is one supposed to test out this PR?

**Comment by danielmarv** [comment]
login but without any activity after the 30 minutes elapse it will auto matically log you out
but i can reduce the time period for the testing because that takes time and after i take it back to normal

**Comment by danielmarv** [comment]
because me i have tested it locally

**Comment by danielmarv** [comment]
i have reduced the time period to 30 seconds now it has logged me out of the system
logout

**Comment by danielmarv** [comment]
because you cannot logout a user when he/she is actively using the system but you can logout an inactive logged in user

**Comment by Baalmart** [comment]
> i have reduced the time period to 30 seconds now it has logged me out of the system logout

Hi @danielmarv .....30 seconds is too short. You can put it back to 10 mins then. Thanks!

**Review by FaithDaka — APPROVED** [review]

**Pull request merged**
