### PR TITLE
Ft road intensity location registry

### PR DESCRIPTION
**Pull request by lilly-muyama**
- What does this PR do?
This PR updates the road intensity options in the location registry, changes the format of the clock in the top bar and makes latitude and longitude fields required.
- What JIRA task is related to this PR?
N/A
- How do I test out this PR?
Git clone this repo `cd AirQo-frontend/locate`. Run `npm install` to get all the necessary dependencies and afterwards run `npm run local`. 

Remember to have the location-registry service running in the backend by running the following docker commands in a separate shell terminal:
a) `docker build -t us.gcr.io/airqo-250220/airqo-location-registry-api .`
b ) `docker run -d -p 4000:8080 us.gcr.io/airqo-250220/airqo-location-registry-api`

- Which end points should are ready for testing?
None

### CODE REVIEW

**Comment by lilly-muyama** [comment]
> 
> 
> Thanks @lilly-muyama
> 
>     * I have just updated the PR description to include the Docker run details for the backend service.
> 
>     * road intensity option in location-registry is kinda disabled, what am I supposed to see?
>       image
> 
>     * How do I test the required latitude and longitude fields?
> 
>     * How do I confirm the changes in the clock format? Image of the previous clock format perhaps?
> 
> 
> In summary, the PR description needs more details under the section of how to test out the PR. Thanks in advance.

The road intensity field is only disabled as are most fields when mobility is set to 'Mobile'.  I've also attached a screenshot of how the clock was before.
Capture

**Comment by lilly-muyama** [comment]
> 
> 
> @lilly-muyama
> Please crosscheck the constants file, there are a number of differences with the staging branch. Are we supposed to merge the latest `staging` branch perhaps? Hmmm... See sample difference:
> image

@Baalmart I believe this has been resolved.

**Comment by sserurich** [comment]
@lilly-muyama , am having challenges running the backend service
image

**Comment by danielogen** [comment]
@lilly-muyama, I've just updated the `docker build` command in the PR description. I hope that's ok

**Pull request merged**
