### PR TITLE
[NetManager] Fix Pending Issues 691

### PR DESCRIPTION
**Pull request by ja-odur**
#### Summary of Changes (What does this PR do?)
- Fixes device maintenance logs (device Overview, adding, updating, deleting a maintenance log)
- Enable adding devices and editing device name(long_name)
- Enable adding site
- Enable deleting a site
- Enable adding user
- Fix device management network chart
- Fix device management chat `last updated` format
- Sort device leaderboard by `uptime` and `deviceName`
- Merge device overview chart components inorder to share `status` state
- Handle redux empty state update

#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [x] I consider this code done
- [ ] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* Fetch and checkout to this branch locally
* Install requirements `npm install`
* Start netmanager application `npm run stage-mac` (macOS) or `npm run stage-pc` (windows Platform)
* Ensure the issues stated in the `Summary of Changes` are fixed

#### What are the relevant tickets?
- [PLAT-691](https://airqoteam.atlassian.net/browse/PLAT-691)

#### Screenshots (optional)

### CODE REVIEW

**Review by Baalmart — COMMENTED** [review]
Thanks @ja-odur :
Just finished some tests....below is a summary. Still reviewingg...

- [x] Fixes device maintenance logs (device Overview, adding, updating, deleting a maintenance log)
- [x] Enable adding devices and editing device name(long_name)
- [x] Enable adding site
- [x] Enable deleting a site
- [ ] Enable adding user
Screenshot 2021-08-06 at 11 38 18

**Comment by ja-odur** [comment]
> Thanks @ja-odur :
> Just finished some tests....below is a summary. Still reviewingg...
> 
> * [x]  Fixes device maintenance logs (device Overview, adding, updating, deleting a maintenance log)
> * [x]  Enable adding devices and editing device name(long_name)
> * [x]  Enable adding site
> * [x]  Enable deleting a site
> * [ ]  Enable adding user
> 
> Screenshot 2021-08-06 at 11 38 18

THis has been fixed @Baalmart.

**Review by NoahNsimbe — APPROVED** [review]
LGTM!

**Review by danielogen — APPROVED** [review]
LGTM

**Pull request merged**
