### PR TITLE
New release updates

### PR DESCRIPTION
**Pull request by Mnoble-19**
#### Summary of Changes (What does this PR do?)

- [x] Update version number for iOS & android for new release.
- [x] Addresses https://github.com/airqo-platform/AirQo-frontend/pull/1182#pullrequestreview-1434088623
- [x] Fixes failing date time tests.

#### Status of maturity (all need to be checked before merging):

- [x] I've tested this locally
- [x] I consider this code done
- [x] This change ready to hit production in its current state
- [x] The title of the PR states what changed and the related issues number (used for the release note).
- [ ] I've included issue number in the "Closes #ISSUE-NUMBER" part of the "[What are the relevant tickets?](#what-are-the-relevant-tickets)" section to [link the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [ ] I've updated corresponding documentation for the changes in this PR.
- [ ] I have written unit and/or e2e tests for my change(s).

#### How should this be manually tested?

- Please include the steps to be done inorder to setup and test this PR.

#### What are the relevant tickets?

- Closes #<enter issue number here>
- [Jira_card_number]() (If exists)

### CODE REVIEW

**Review by NoahNsimbe — APPROVED** [review]
LGTM. Thanks @Mnoble-19

**Review by NoahNsimbe — APPROVED** [review]
LGTM. Thanks @Mnoble-19

**Review by Baalmart — CHANGES_REQUESTED** [review]
I will review this PR further. Something seems off, I am on phone now. Shall review in greater details within the nextb2 hours. @Mnoble-19

**Comment by Baalmart** [comment]
@Mnoble-19 perhaps the name of the PR branch is what confused me! 😁😁😁 I am curious as to why the branch is named: "move to production"

**Review by Baalmart — APPROVED** [review]

**Comment by Mnoble-19** [comment]
> @Mnoble-19 perhaps the name of the PR branch is what confused me! 😁😁😁 I am curious as to why the branch is named: "move to production"

Let me give a more appropriate name. I meant `move-to-production` as the changes here are for our new release in production, but let me fix it

**Pull request merged**
