### PR TITLE
[NetManager] Add Spatial heatmap

### PR DESCRIPTION
**Pull request by ja-odur**
#### Summary of Changes (What does this PR do?)
- Adds heatmap to dashboard

#### Is this change ready to hit production in its current state?
- [ ] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [ ] I consider this code done
- [ ] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* Pull and checkout to this [branch]() locally
* Install node requirements `npm install`
* Start the application `npm run stage-mac` (on mac) or `npm run stage-pc` (on windows platform)
**NB** setup the locally, the [predict](https://github.com/airqo-platform/AirQo-api/pull/207) microservice to run on port 3000

#### What are the relevant tickets?
- [PLAT-299](https://airqoteam.atlassian.net/browse/PLAT-299)

#### Screenshots (optional)

image

### CODE REVIEW

**Review by sserurich — APPROVED** [review]
spatial heatmap looks okay, but there was difference in sensor values & values that occur on hover.. but this is something that will be sorted after demo to users on whether to completely remove the sensor values

**Review by lilly-muyama — APPROVED** [review]
LGTM. We might need to re-visit the toggling. Showing both the device readings and the heatmap seems something that only a few users would be interested in.

**Comment by danielogen** [comment]
Hi @ja-odur: Things are looking cool. I just noticed that clicking the filter at the bottom left corner breaks the app.
Screenshot 2020-11-25 at 17 50 26

**Comment by ja-odur** [comment]
> Hi @ja-odur: Things are looking cool. I just noticed that clicking the filter at the bottom left corner breaks the app.
> Screenshot 2020-11-25 at 17 50 26

Thank you.Let me replicate and fix

**Review by Priscilla-AL — APPROVED** [review]
looks good

**Comment by ja-odur** [comment]
> > Hi @ja-odur: Things are looking cool. I just noticed that clicking the filter at the bottom left corner breaks the app.
> > Screenshot 2020-11-25 at 17 50 26
> 
> Thank you.Let me replicate and fix

@danielogen I have looked into this but failed to replicate the error. maybe you could try again to ensure the error is consistent.

**Pull request merged**
