### PR TITLE
[NET] Implementation of the faulty device view

### PR DESCRIPTION
**Pull request by OchiengPaul442**
#### Summary of Changes (What does this PR do?)
Added a view for displaying faulty devices in Netmanager

- This commit introduces a new view in Netmanager that displays a list of devices that have reported errors or malfunctions within the last 24 hours. This feature is currently only available in the production environment and not yet accessible in staging.

#### Status of maturity (all need to be checked before merging):

- [x] I've tested this locally
- [x] I consider this code done
- [x] This change ready to hit production in its current state

#### Screenshots (optional)
image
image

### CODE REVIEW

**Review by Mnoble-19 — APPROVED** [review]

**Review by Baalmart — COMMENTED** [review]
Thanks @OchiengPaul442 
**A few feedback points:**
1. the page loads endlessly, could it be expected behaviour? **See attached screenshot**.
2. I am also curious about the unit testing approach being utilised. Could you share a link to a resource you are utilising for going about your unit testing?
Thanks again!
Screenshot 2023-08-21 at 19 30 07

**Comment by OchiengPaul442** [comment]
Hey @Baalmart,The intended behaviour is for the loading to stop once a response from the API is received but the endpoint for faulty devices is not returning any data, which is causing the continuous loading. As I mentioned in my “summary of changes,” there won’t be any response from the endpoint for faulty devices because it is only available in production, not staging. This means that the preview will continue to load indefinitely since there is no response from the API on staging environment.
cc: @Mnoble-19

**Comment by OchiengPaul442** [comment]
Also @Baalmart , this is the resource i use to guide me when carrying out the unit testing:
https://testing-library.com/docs/react-testing-library/example-intro

thanks.

**Comment by Baalmart** [comment]
> https://testing-library.com/docs/react-testing-library/example-intro

thanks @OchiengPaul442

**Comment by OchiengPaul442** [comment]
> Great work @OchiengPaul442 .
> 
> Let's remove that spinner if no data is returned. Avoiding a second PR to fix this.
> 
> Screenshot from 2023-08-22 15-18-44

Thanks, @Codebmk, I will work on that.

**Pull request closed without merging**
