### PR TITLE
device details page

### PR DESCRIPTION
**Pull request by sserurich**
**What does this PR do?**
    - Displays device details page with  graph for device uptime
  
**Which JIRA card(s)?**
    - [https://airqoteam.atlassian.net/jira/software/projects/NET/boards/28?selectedIssue=NET-86](https://airqoteam.atlassian.net/jira/software/projects/NET/boards/28?selectedIssue=NET-86)
**How do I test out this PR?**
-  git fetch branch  **ft-network-uptime-details-page**  
- change directory to airqo-frontend/locate (locate project)
- run npm install to get all the necessary dependencies. 
- After, run npm run local  
- Remember to have the backend services running as well from master branch for device_registry 
 - Also ensure device-monitoring backend is running from this [PR ](https://github.com/airqo-platform/AirQo-api/pull/116). 
- Ensure you have devices with actual channelIds in your local db

**Which changes should be /are ready for testing?**
 - Check out the details page by clicking on device registry and clicking on the highlighted icon(view details page) or click on name of the device.
image

image

### CODE REVIEW

**Comment by sserurich** [comment]
> @sserurich
> There are quite a number of differences between the constants files in `staging` (https://github.com/airqo-platform/AirQo-frontend/blob/staging/locate/src/config/constants.js) and this PR's branch. See sample difference below:
> image
> 
> Please review and probably merge` staging` in this PR's branch?
> 
> cc: @lilly-muyama

@Baalmart  @lilly-muyama , I have merged in the updated staging.. and endpoints in constants.js  have now updated.

**Comment by sserurich** [comment]
> @sserurich
> Following the PR description, I have gone like this:
> 
> * `cd AirQo-frontend/locate` [ft-network-uptime-details-page BRANCH]
> * `npm install`
> * `npm run local`
> * Switched to a new tab in my Shell terminal
> * `cd AirQo-api/src/device-monitoring` [master BRANCH]
> * `python3 -m venv ~/env`
> * `source ~/env/bin/activate`
> * `flask run`
> * Switched to a new tab in my Shell terminal
> * `cd AirQo-api/src/device-registry` [master BRANCH]
> * `npm install`
> * `npm run dev-mac`
> 
> Output I get on frontend does not load graph, what could I be missing?
> image

@Baalmart , it might have been the local port your device monitoring service is running on.   Also I have created a new PR for backend device monitoring which you should run in parallel with this.

**Comment by lilly-muyama** [comment]
@sserurich , is the date in the online status a placeholder or? Because I've seen a device with 100% uptime in the past 24hrs on the graph yet the online status shows it was last updated on 9th July.

**Comment by sserurich** [comment]
> @sserurich , is the date in the online status a placeholder or? Because I've seen a device with 100% uptime in the past 24hrs on the graph yet the online status shows it was last updated on 9th July.
@lilly-muyama , this shouldn't be a problem once the cron job is running successfully @danielogen  was looking into it. @danielogen  we need to get this resolved.

**Comment by danielogen** [comment]
> > @sserurich , is the date in the online status a placeholder or? Because I've seen a device with 100% uptime in the past 24hrs on the graph yet the online status shows it was last updated on 9th July.
> > @lilly-muyama , this shouldn't be a problem once the cron job is running successfully @danielogen  was looking into it. @danielogen  we need to get this resolved.

This is kindly noted @sserurich.

**Pull request merged**
