### PR TITLE
Minor fix to loader message #846

### LINKED ISSUE #846: Change the AirQo docs loader message from "Please wait..." to "Loading..."
**Describe the solution you'd like**
Before the [AirQo docs](https://staging-docs.airqo.net/#/) content loads, a loader screen is presented with a "Please wait..." message. We want to update the message to "Loading..."

**Additional context**
The line of code to change is https://github.com/airqo-platform/AirQo-frontend/blob/d01f8a49fec0c33dfebdcf9f5cf10630c0f2a3a3/docs/index.html#L19

### PR DESCRIPTION
**Pull request by sotiriszogos**
#### Summary of Changes (What does this PR do?)
- Closes #846 

#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [x] I consider this code done
- [x] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
- Static code analysis

#### What are the relevant tickets?
- #846

#### Screenshots (optional)

### CODE REVIEW

**Comment by 123MwanjeMike** [comment]
Thanks @sotiriszogos 
Kindly update the PR description checkboxes to reflect the readiness of the PR.

**Review by 123MwanjeMike — APPROVED** [review]
LGTM

**Review by Codebmk — APPROVED** [review]
LGTM

**Review by Baalmart — APPROVED** [review]
LGTM

**Pull request merged**
