### PR TITLE
[NetManager] Add site and  location name

### PR DESCRIPTION
**Pull request by ja-odur**
#### Summary of Changes (What does this PR do?)
- Add site and location name to device registry table. Removed columns (device ID, location ID)
- Resolves this issue [232](https://github.com/airqo-platform/AirQo-frontend/issues/232)

#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [x] I consider this code done
- [x] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* Fetch this branch locally
* Install requirements using `npm install`
* Start Application using `npm run stage-mac` (MacOs) or `npm run stage-pc` (Windows PC)
* Check the above mentioned columns

#### What are the relevant tickets?
- [PLAT-525](https://airqoteam.atlassian.net/browse/PLAT-525)

#### Screenshots (optional)

### CODE REVIEW

**Review by lilly-muyama — APPROVED** [review]
Works as expected. However, we have a standard convention for the location name. Maybe an issue could be raised to resolve this for devices which aren't following the convention or where the site name is exactly the same as the location name

**Review by sserurich — APPROVED** [review]
This worked ok as expected.. however if  we can add someother attribute for user to know the period when device was at particular site e.g AQ_94 was in Nakawa for some time and seems it was moved to Makerere and now when you run device test, it returns makerere coordinates.

**Comment by sserurich** [comment]
> This worked ok as expected.. however if we can add someother attribute for user to know the period when device was at particular site e.g AQ_94 was in Nakawa for some time and seems it was moved to Makerere and now when you run device test, it returns makerere coordinates.

@ja-odur ,

**Comment by danielogen** [comment]
> Works as expected. However, we have a standard convention for the location name. Maybe an issue could be raised to resolve this for devices which aren't following the convention or where the site name is exactly the same as the location name

Good point @lilly-muyama

**Review by danielogen — APPROVED** [review]
LGTM

**Review by Priscilla-AL — APPROVED** [review]
LGTM

**Pull request merged**
