### PR TITLE
[Netmanager] Export data options

### PR DESCRIPTION
**Pull request by Codebmk**
#### Summary of Changes (What does this PR do?)

- Add export data by devices, sites and airqlouds
- Updated to appropriate error message

#### Status of maturity (all need to be checked before merging):

- [ ] I've tested this locally
- [ ] I consider this code done
- [ ] This change ready to hit production in its current state
- [ ] The title of the PR states what changed and the related issues number (used for the release note).
- [ ] I've included issue number in the "Closes #ISSUE-NUMBER" part of the "[What are the relevant tickets?](#what-are-the-relevant-tickets)" section to [link the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [ ] I've updated corresponding documentation for the changes in this PR.
- [ ] I have written unit and/or e2e tests for my change(s).

#### How should this be manually tested?

- To Export by device. Check aq_g534

#### What are the relevant tickets?

- Closes #<enter issue number here>
- [AN-253](https://airqoteam.atlassian.net/browse/AN-253?atlOrigin=eyJpIjoiYzU2NzcxZGZmM2IxNDFiNGI1MTE1NGYwYTdmNWVmMjQiLCJwIjoiaiJ9)
- [AN-251](https://airqoteam.atlassian.net/browse/AN-251?atlOrigin=eyJpIjoiMDAwN2E0Yjc3NjYwNGY1MWEwOTM4MTMwMjQ1ZDAyZTAiLCJwIjoiaiJ9)

#### Screenshots (optional)
Screenshot from 2023-02-14 15-56-38

[AN-253]: https://airqoteam.atlassian.net/browse/AN-253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by Baalmart — COMMENTED** [review]
Thanks @Codebmk , this is great work. 
I am getting CORS error on the deploy preview link as seen in the attached screenshot.

Otherwise, I am still testing things
Screenshot 2023-02-15 at 12 09 42

**Comment by Baalmart** [comment]
@Codebmk 
Screenshot 2023-02-16 at 17 42 20

**Review by NoahNsimbe — APPROVED** [review]
LGTM

**Comment by Codebmk** [comment]
@Baalmart kindly try again or try switching browsers. It's working fine.

**Comment by NoahNsimbe** [comment]
> @Baalmart kindly try again or try switching browsers. It's working fine.

I think NOT Found is not an error. Doesn't it mean not found i.e data not found ? @Codebmk

**Comment by NoahNsimbe** [comment]
> @Baalmart kindly try again or try switching browsers. It's working fine.

I think NOT Found is not an error. Doesn't it mean not found i.e data not found ? @Codebmk

> @Baalmart kindly try again or try switching browsers. It's working fine.

I think NOT Found is not an error. Doesn't it mean not found i.e data not found ? @Codebmk

**Comment by Codebmk** [comment]
Yes @NoahNsimbe it is likely that at that time no data was being found.

**Comment by NoahNsimbe** [comment]
> Yes @NoahNsimbe it is likely that at that time no data was being found.

So it's not an error..right??. The system was just being sincere

**Comment by Codebmk** [comment]
@NoahNsimbe what is your point?? 404 is an error

**Comment by NoahNsimbe** [comment]
> @NoahNsimbe what is your point?? 404 is an error code

Yeah. From the discussions we had, the API returns 404 if there is no data and 200 if there is data.

**Comment by Baalmart** [comment]
> > @NoahNsimbe what is your point?? 404 is an error code
> 
> Yeah. From the discussions we had, the API returns 404 if there is no data and 200 if there is data.

Thanks for the clarifications @NoahNsimbe 

We shall need to revisit this 404 discussion. It could be misleading from a Frontend perspective.

We might want to consider 200 OK success and empty array of data.....just to eradicate any confusions. 

Thanks again!

cc: @Codebmk

**Review by Baalmart — APPROVED** [review]
LGTM, thanks @Codebmk

**Pull request merged**
