### PR TITLE
[NetManager] Device registry fixes

### PR DESCRIPTION
**Pull request by ja-odur**
#### Summary of Changes (What does this PR do?)
- Adds new fields (Site Name, Location Name) to add device form.
- Fixes the typing lag in the device registry form

#### Is this change ready to hit production in its current state?
- [ ] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [ ] I consider this code done
- [ ] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* Fetch this branch locally.
* Run `npm install`
* Start application `npm run stage-mac` (MacOS) or `npm run stage-pc`

#### What are the relevant tickets?
- [N/A]()

#### Screenshots (optional)

### CODE REVIEW

**Review by lilly-muyama — APPROVED** [review]

**Review by sserurich — APPROVED** [review]
Looks good as works as expected, the only caveat (minor thing) was that incase device already exists , the form disappears & all the info gets lost meaning user must re-enter everything

**Comment by sserurich** [comment]
> Looks good as works as expected, the only caveat (minor thing) was that incase device already exists , the form disappears & all the info gets lost meaning user must re-enter everything.. @ja-odur

also just confirming whether entering the location name & site name here at the device is the final solution for capturing the site.

**Comment by Baalmart** [comment]
> > Looks good as works as expected, the only caveat (minor thing) was that incase device already exists , the form disappears & all the info gets lost meaning user must re-enter everything.. @ja-odur
> 
> also just confirming whether entering the location name & site name here at the device is the final solution for capturing the site.

Thanks @sserurich for the review...
Just to share some clarification, this is the final step towards ensuring that the hardware team utilise ONLY Netmanager going forward. It mimics the current way they have been adding devices on the admin page of the AirQo website. 

As for capturing site information, we intend to keep most of this site registry as background processes which do not require a user to enter anything from the frontend. Ideally, site information will just be generated from the GPS coordinates associated with a device.....a completely background process that does not necessarily need a UI.

**Review by Baalmart — CHANGES_REQUESTED** [review]
This looks good to me, appears as described in the PR description.

Could we also update the EDIT tab and add these fields?
I assume that a user could also want to make some edits to this site name at any point in the future.

**Comment by ja-odur** [comment]
> Looks good as works as expected, the only caveat (minor thing) was that incase device already exists , the form disappears & all the info gets lost meaning user must re-enter everything.. @ja-odur

@sserurich This is fixed

**Comment by ja-odur** [comment]
> This looks good to me, appears as described in the PR description.
> 
> Could we also update the EDIT tab and add these fields?
> I assume that a user could also want to make some edits to this site name at any point in the future.

@Baalmart This has been fixed too

**Pull request merged**
