### PR TITLE
[Analytics] Added dropdown menu to device Status table

### PR DESCRIPTION
**Pull request by OchiengPaul442**
#### key issue
- No dropdown menu on the device status table

#### Notice
- need to add an endpoint for deleting batch on the dropdown list
- Errors when using Flowbite or when initializing flowbite js in the project 

#### Summary of Changes
- Added the dropdown menu on the device status table.
- Created a dropdown component in the components folder which can be reused on other tables if needed.
- created a modal to confirm the deletion of batch device

#### Status of maturity
- [x] Dropdown added and functional.
- [x] Dropdown items added as well.
- [x] Added the endpoint for the view report  
- [x] No endpoint for the delete option yet 

#### What are the relevant tickets?
- [Jira_card_number]() [AN-419](https://airqoteam.atlassian.net/browse/AN-419)
https://airqoteam.atlassian.net/browse/AN-419

#### Screenshots

Table
image

dropdown view
image

dropdown list
image

[AN-419]: https://airqoteam.atlassian.net/browse/AN-419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by Baalmart — COMMENTED** [review]
thanks @OchiengPaul442 , PR looks amazing. I am just not sure of how to reach the dropdown menu.

It could just be on my end I guess. cc: @NoahNsimbe

**Review by Baalmart — COMMENTED** [review]
thanks @OchiengPaul442 , PR looks amazing. I am just not sure of how to reach the dropdown menu.

It could just be on my end I guess. cc: @NoahNsimbe

**Comment by OchiengPaul442** [comment]
@NoahNsimbe am waiting for details from @PaulZana on what endpoint to include for the delete item button but for now, i worked with what was already provided ie the view report endpoint.

**Comment by NoahNsimbe** [comment]
> @NoahNsimbe am waiting for details from @PaulZana on what endpoint to include for the delete item button but for now, i worked with what was already provided ie the view report endpoint.

 Let me share the delete endpoint via slack @OchiengPaul442

**Comment by OchiengPaul442** [comment]
That would be great thanks @NoahNsimbe

**Comment by NoahNsimbe** [comment]
> thanks @OchiengPaul442 , PR looks amazing. I am just not sure of how to reach the dropdown menu.
> 
> It could just be on my end I guess. cc: @NoahNsimbe

@Baalmart you can access the collocate table using the left panel

**Comment by OchiengPaul442** [comment]
@Baalmart the dropdown menu is under common/components/collocation/Dropdowns 
it's a new component I created and imported to the device status table

**Comment by Baalmart** [comment]
> here

Thanks @NoahNsimbe , please see attached screenshot. What am I missing? cc: @OchiengPaul442 
Screenshot 2023-06-06 at 14 45 43

**Comment by OchiengPaul442** [comment]
@Baalmart the dropdown is on each device item on the table on the extreme right:

please check the screenshot below

Screenshot (47)

**Comment by Baalmart** [comment]
> @Baalmart the dropdown is on each device item on the table on the extreme right:
> 
> please check the screenshot below
> 
> Screenshot (47)

Thanks @OchiengPaul442 , this has been realised. Much clear now, must have been tired earlier. :)

**Review by Baalmart — APPROVED** [review]
Thanks @OchiengPaul442 , this looks good to me.

PR will be merged after more approvals from at least 2 people in the following list:
1. @FaithDaka 
2. @Codebmk 
3. @NoahNsimbe

**Review by Baalmart — APPROVED** [review]
Thanks @OchiengPaul442 , this looks good to me.

PR will be merged after more approvals from at least 2 people in the following list:
1. @FaithDaka 
2. @Codebmk 
3. @NoahNsimbe

**Review by NoahNsimbe — APPROVED** [review]
LGTM

**Pull request merged**
