### PR TITLE
update mobile app release notes

### LINKED ISSUE #972: [docs] update mobile app release notes
**What were you trying to achieve?**
The [mobile app release notes](https://ft-addteststodocsci-docs-preview-w7kzhvlewq-ew.a.run.app/#/mobile_app/release_notes?id=_1218-2021-09-23) do not seem to reflect the [latest release](https://github.com/airqo-platform/AirQo-frontend/releases/tag/v2.0.11).
Screenshot from 2022-11-27 06-57-15

**What are the expected results?**
The[ mobile app release notes](https://ft-addteststodocsci-docs-preview-w7kzhvlewq-ew.a.run.app/#/mobile_app/release_notes?id=_1218-2021-09-23) should include the[latest release](https://github.com/airqo-platform/AirQo-frontend/releases/tag/v2.0.11).

**What are the received results?**

**What are the steps to reproduce the issue?**
Visit [mobile app release notes](https://ft-addteststodocsci-docs-preview-w7kzhvlewq-ew.a.run.app/#/mobile_app/release_notes?id=_1218-2021-09-23)

**In what environment did you encounter the issue?**

**Additional context**
Any other information you would like to share?

### PR DESCRIPTION
**Pull request by HassanBahati**
#### Summary of Changes (What does this PR do?)

- Updated the [mobile app release notes](https://ft-addteststodocsci-docs-preview-w7kzhvlewq-ew.a.run.app/#/mobile_app/release_notes?id=_1218-2021-09-23) to reflectt the [latest release](https://github.com/airqo-platform/AirQo-frontend/releases/tag/v2.0.11).

#### Status of maturity (all need to be checked before merging):

- [x] I've tested this locally
- [x] I consider this code done
- [x] This change ready to hit production in its current state
- [x] The title of the PR states what changed and the related issues number (used for the release note).
- [x] I've included issue number in the "Closes #ISSUE-NUMBER" part of the "[What are the relevant tickets?](#what-are-the-relevant-tickets)" section to [link the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [x] I've updated corresponding documentation for the changes in this PR.

#### How should this be manually tested?
1. Pull the code from this branch
2. Visit  [mobile app release notes](https://github.com/airqo-platform/AirQo-frontend/releases/tag/v2.0.11)

#### What are the relevant tickets?
#972 

- Closes #972

### CODE REVIEW

**Comment by HassanBahati** [comment]
@NoahNsimbe @123MwanjeMike is there anything in [latest release](https://github.com/airqo-platform/AirQo-frontend/releases/tag/v2.0.11) is doesn't seem to be captured?

**Comment by NoahNsimbe** [comment]
Hi @HassanBahati, thanks for bringing this up. There are some changes that haven't been stated. We shall be sharing them by the end of this week. cc @BenjaminSsempala

**Comment by HassanBahati** [comment]
> Hi @HassanBahati, thanks for bringing this up. There are some changes that haven't been stated. We shall be sharing them by the end of this week. cc @BenjaminSsempala

Okay please, lets wait on the changes

**Comment by BenjaminSsempala** [comment]
@HassanBahati 
Other changes include:
- Bug fixes for failure on startup.
- Nearest Location Functionality.
CC: @NoahNsimbe

**Comment by NoahNsimbe** [comment]
> > @HassanBahati Other changes include:
> > ```
> > * Bug fixes for failure on startup.
> > 
> > * Nearest Location Functionality.
> >   CC: @NoahNsimbe
> > ```
> 
> @BenjaminSsempala thanks. They've been added.

Thanks @HassanBahati and @BenjaminSsempala

**Review by Baalmart — COMMENTED** [review]
Awesome, thanks @HassanBahati , this is much appreciated!

- How do we keep these release notes in sync with actual development works on the mobile app?
- Is there a way these release notes can be integrated in the version control process for the mobile app development so as to add more automation to the process?

**Review by NoahNsimbe — APPROVED** [review]
LGTM

**Review by Baalmart — APPROVED** [review]

**Comment by HassanBahati** [comment]
> Awesome, thanks @HassanBahati , this is much appreciated!
> 
>     * How do we keep these release notes in sync with actual development works on the mobile app?
> 
>     * Is there a way these release notes can be integrated in the version control process for the mobile app development so as to add more automation to the process?

@Baalmart let me look into this, and see how we can have a continuous sync.

**Pull request merged**
