### PR TITLE
[Website] Ft Board Members

### PR DESCRIPTION
**Pull request by FaithDaka**
#### Summary of Changes (What does this PR do?)

- Board members backend schema
- Board members section on about-us page

#### Status of maturity (all need to be checked before merging):

- [x] I've tested this locally
- [x] I consider this code done
- [x] This change ready to hit production in its current state
- [x] The title of the PR states what changed and the related issues number (used for the release note).
- [x] I've included issue number in the "Closes #ISSUE-NUMBER" part of the "[What are the relevant tickets?](#what-are-the-relevant-tickets)" section to [link the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

#### How should this be manually tested?

- View board members section through the deploy preview

#### What are the relevant tickets?

- [WEB-345]

#### Screenshots 
image

[WEB-345]: https://airqoteam.atlassian.net/browse/WEB-345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by FaithDaka** [comment]
@123MwanjeMike Why aren't the changes within this branch reflecting in the deploy preview?

**Comment by 123MwanjeMike** [comment]
> @123MwanjeMike Why aren't the changes within this branch reflecting in the deploy preview?

Hi @FaithDaka, please note that the website only has one channel for preview deployment. This means that it can only handle one PR at a time i.e the most recent changes to the /website folder in #996 override those in this PR

**Comment by Baalmart** [comment]
> #996

Hi @123MwanjeMike , please shed more light on this.
The referenced PR has just been merged.
Any additional concerns?

**Comment by 123MwanjeMike** [comment]
> > #996
> 
> Hi @123MwanjeMike , please shed more light on this. The referenced PR has just been merged. Any additional concerns?

No concern really.
Changes in this PR can now be previewed given that the other was merged

**Review by 123MwanjeMike — COMMENTED** [review]
Thanks @FaithDaka 
I can see the “meet the board section” although we may need a sample board record added to the dev db for a complete review

**Comment by FaithDaka** [comment]
Sample has been added @123MwanjeMike

**Review by 123MwanjeMike — APPROVED** [review]
Thanks @FaithDaka 
LGTM

image

**Pull request merged**
