### PR TITLE
[Website] Website Fixes

### PR DESCRIPTION
**Pull request by ja-odur**
#### Summary of Changes (What does this PR do?)
- Remove pop-up model from the FAQ section
- Add terms of use link in the footer
- Adjust default map zoom to focus on KLA nodes

#### Is this change ready to hit production in its current state?
- [X] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [X] I consider this code done
- [X] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* Pleas follow the instructions in the `README.md` file

#### What are the relevant tickets?
- [PLAT-886](https://airqoteam.atlassian.net/browse/PLAT-886)

### CODE REVIEW

**Review by Baalmart — COMMENTED** [review]
On attempting to build the docker images..... @ja-odur care to share some tips on what could be the challenge?
Screenshot 2021-11-24 at 15 00 58

**Review by NoahNsimbe — COMMENTED** [review]
Managed to run the website locally after making changes to the docker-compose file to enable building on a M1.
I realised all the map nodes were grey, is it because my database dump is out-dated ?? @ja-odur 
Otherwise all looks good to me

**Comment by Baalmart** [comment]
> Managed to run the website locally after making changes to the docker-compose file to enable building on a M1. I realised all the map nodes were grey, is it because my database dump is out-dated ?? @ja-odur Otherwise all looks good to me

I personally failed to run. Perhaps shall sync with you tomorrow to see what I could have missed in the run procedure. Besides the grey nodes, were the issues in the PR description addressed? @NoahNsimbe

**Comment by NoahNsimbe** [comment]
> > Managed to run the website locally after making changes to the docker-compose file to enable building on a M1. I realised all the map nodes were grey, is it because my database dump is out-dated ?? @ja-odur Otherwise all looks good to me
> 
> I personally failed to run. Perhaps shall sync with you tomorrow to see what I could have missed in the run procedure. Besides the grey nodes, were the issues in the PR description addressed? @NoahNsimbe

Yes, they were addressed @Baalmart

**Comment by ja-odur** [comment]
> On attempting to build the docker images..... @ja-odur care to share some tips on what could be the challenge? Screenshot 2021-11-24 at 15 00 58

@Baalmart This is a missing UID value. Add these 
```
UID=1000
DEV_UID=1000
```

to your `.env` file and try again

**Comment by ja-odur** [comment]
> Managed to run the website locally after making changes to the docker-compose file to enable building on a M1. I realised all the map nodes were grey, is it because my database dump is out-dated ?? @ja-odur Otherwise all looks good to me

Yes @NoahNsimbe, the db is out of date. There is an endpoint to repopulate the db with recent values but cant remember it right now

**Review by NoahNsimbe — APPROVED** [review]
LGTM

**Review by Baalmart — COMMENTED** [review]
Thanks @ja-odur , I can now run successfully. A few observations:

1. The zoom level on Kampala is working well! Thanks!
2. I am not able to see the terms and conditions in the footer section. Not sure why. Please see attached screenshot. If they exist, could you make them standout or make them visible? If someone misses them at first glance, then it is of no benefit to anyone. 
3. The FAQs models are working pretty well. Thanks!
4. I have also observed that the majority of the nodes are grey. While the ones not grey are zero values. Guess we might also need to look into that zero values issue. You can also see another screenshot depicting this.
Screenshot 2021-11-30 at 07 44 34
Screenshot 2021-11-30 at 07 45 14

**Review by Baalmart — APPROVED** [review]
LGTM

**Pull request merged**
