### PR TITLE
[Netmanager] Implement a horizontal loader

### PR DESCRIPTION
**Pull request by OchiengPaul442**
#### Summary of Changes (What does this PR do?)
- Made the Loader darker yellow for better visibility.
- Simplified the Horizontal loader component code.
- Cleaned up the edit device section code and removed the circular loader from the recall and deploy buttons.
- Prepared the loader for future use on sections with disabled delete and edit functions by adding the loading state.
- Added a horizontal loader on top of these views:
1. Device registry: add device and soft add device
2. Site Registry: add site
3. Users: assigned users
4. Also All parts with edit and delete functionality

#### Status of maturity (all need to be checked before merging):

- [x] I've tested this locally
- [x] I consider this code done

- [Jira_card_number]() [AN-479](https://airqoteam.atlassian.net/browse/AN-479)

#### Screenshots (optional)
image

[AN-479]: https://airqoteam.atlassian.net/browse/AN-479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by Baalmart — COMMENTED** [review]
thanks @OchiengPaul442 , could we make this loader have another "more visible" color?

1. Have we tried White? Since it is operating with a blue navbar?
2. Have we explored other "more visible" loader options?

Thanks again!

**Comment by OchiengPaul442** [comment]
Hey @Baalmart, thanks for your feedback. for now, I have only tried out two colors which are red and yellow but will keep trying different colors that are more visible.

**Comment by Baalmart** [comment]
> Hey @Baalmart, thanks for your feedback. for now, I have only tried out two colors which are red and yellow but will keep trying different colors that are more visible.

thanks @OchiengPaul442 ......we could perhaps continue and also consider WHITE perhaps? Have you tried it out?
Also, can this loader be **beneath our blue navbar**? How does that sound like? Just for more visibiliy?

Thanks again!

**Review by Baalmart — APPROVED** [review]

**Review by Baalmart — CHANGES_REQUESTED** [review]
Hi @OchiengPaul442 , I am not sure what the problem could be but the nodes on the landing page are not loading up. And yet the API is working somehow fine? **Attached is a screenshot** of the console logs. Can you investigate the cause?

Screenshot 2023-06-27 at 22 13 52

**Review by Baalmart — APPROVED** [review]
Just noticed that the recently shared issue is also in deployment so we are good. Thanks @OchiengPaul442 

I guess it will be addressed in a future PR.

**Pull request merged**
