### PR TITLE
Website maintenance

### PR DESCRIPTION
**Pull request by danielogen**
#### Summary of Changes (What does this PR do?)

- [x] Split deployment yaml files for staging and production environment on app engine
- [x] Updated README file to reflect the changes

#### Is this change ready to hit production in its current state?
- [ ] Yes
- [X] No

#### Status of maturity (all need to be checked before merging):

- [ ] I consider this code done
- [x] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* Follow the instruction in the README.md file

#### What are the relevant tickets?
- None

#### Screenshots (optional)

### CODE REVIEW

**Review by Baalmart — COMMENTED** [review]
Not sure about the status of this PR. Still a WIP or can be discarded? @danielogen @NoahNsimbe

**Comment by NoahNsimbe** [comment]
> Not sure about the status of this PR. Still a WIP or can be discarded? @danielogen @NoahNsimbe

Let me update it @Baalmart cc @danielogen

**Review by 123MwanjeMike — APPROVED** [review]

**Comment by Baalmart** [comment]
> > Not sure about the status of this PR. Still a WIP or can be discarded? @danielogen @NoahNsimbe
> 
> Let me update it @Baalmart cc @danielogen

thanks @NoahNsimbe , please advise on next step....is it now up to date? And `ready to merge` oba?

**Review by Baalmart — APPROVED** [review]
LGTM

**Pull request merged**
