### PR TITLE
[NetManager] Mobile Responsivenes part 2

### PR DESCRIPTION
**Pull request by ja-odur**
#### Summary of Changes (What does this PR do?)
- Mobile responsiveness for device view page
- Fixes these issues
   -- [issue 222](https://github.com/airqo-platform/AirQo-frontend/issues/222)
  -- [issue 212](https://github.com/airqo-platform/AirQo-frontend/issues/212)
#### Is this change ready to hit production in its current state?
- [ ] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [ ] I consider this code done
- [ ] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* Fetch this branch locally
* Install requirements using `npm install`
* Start Application using `npm run stage-mac` (MacOs) or `npm run stage-pc` (Windows PC)
* Navigate the device details overview, the page should be responsive.
* The issues stated above should be resolved.

#### What are the relevant tickets?
- [PLAT-483](https://airqoteam.atlassian.net/browse/PLAT-483)

#### Screenshots (optional)

### CODE REVIEW

**Review by NoahNsimbe — APPROVED** [review]
LGTM

**Review by lilly-muyama — APPROVED** [review]
Works well

**Review by danielogen — CHANGES_REQUESTED** [review]
Works well. I just realize some small issue with `battery voltage` card. The text `last 28...` 
Screenshot 2021-04-22 at 19 28 53

**Comment by ja-odur** [comment]
> Works well. I just realize some small issue with `battery voltage` card. The text `last 28...`
> Screenshot 2021-04-22 at 19 28 53

@danielogen fixed

**Review by danielogen — APPROVED** [review]
LGTM

**Pull request merged**
