### PR TITLE
battery voltage feature ,sensor correlation visual &  added uptime threshold

### PR DESCRIPTION
**Pull request by sserurich**
…, device sensor correlation
updated uptime threshold for device & network, device battery voltage feature…

**What does this PR do?**
    - adds threshold to device & network visuals
    - creates battery voltage graph on device details page
   - creates device sensor correlation graph on device details page
  
**Which JIRA card(s)?**
    - [https://airqoteam.atlassian.net/browse/NET-91](https://airqoteam.atlassian.net/browse/NET-91)
    - [https://airqoteam.atlassian.net/browse/NET-87](https://airqoteam.atlassian.net/browse/NET-87)
**How do I test out this PR?**
-  git fetch branch  **ft-battery-voltage**  
- change directory to airqo-frontend/locate (netmanager project)
- run npm install to get all the necessary dependencies. 
- After, run npm run local  
**Which changes should be /are ready for testing?**
 - Confirm that sensor correlation graph displays on the device details page
 - Comfirm threshold is added on network uptime and device uptime 
 - Check that battery voltage graph is displayed on device details page.
NB: Ensure to run the backend services for device registry and device monitoring using this [PR](https://github.com/airqo-platform/AirQo-api/pull/131)
image

image
image

### CODE REVIEW

**Comment by Baalmart** [comment]
> For some reason, I keep getting the error message attached. Not sure what I'm doing wrong.
> 
> Screenshot 2020-08-11 at 19 00 09

Could you try adding .env inside the netmanager project folder. Just use the "old" one from Locate.

**Comment by danielogen** [comment]
> > For some reason, I keep getting the error message attached. Not sure what I'm doing wrong.
> > Screenshot 2020-08-11 at 19 00 09
> 
> Could you try adding .env inside the netmanager project folder. Just use the "old" one from Locate.

oh ok, that should be it. Let me try.

**Comment by sserurich** [comment]
> * Confirm that sensor correlation graph displays on the device details page
>   This does not display on a device I selected, could it be because that device does not exist?
>   image
> * Comfirm threshold is added on network uptime and device uptime
>   This is kinda visible on the device I selected.
>   image
> * Check that battery voltage graph is displayed on device details page.
>   I am not able to see anything, could it be that some devices are inactive? Probably share a device name I can test this PR with? For context, I checked out:` http://localhost:5000/device/1020600`
>   image

@Baalmart , ensure the backend services are running simultaneously: device monitoring & device registry

**Review by Baalmart — APPROVED** [review]
Works as expected now.

**Pull request merged**
