### PR TITLE
Ft branding segregation

### PR DESCRIPTION
**Pull request by danielogen**
- **What does this PR do?**
Users able to see the logo of their organization 

- **How do I test it out?**
cd `AirQo-frontend/netmanager`
```
npm install 

For Windows:
npm run stage-pc

For Mac:
npm run stage-mac
```
Try to the logo as KCCA or AirQo to see how the logo displayed varies
- Which JIRA card is associated?

- **Any other considerations?**
NONE

Screenshot 2020-10-13 at 06 12 18
Screenshot 2020-10-13 at 06 11 35

### CODE REVIEW

**Review by ja-odur — CHANGES_REQUESTED** [review]
I think it's better if the icons take the same space/width in the topbar regardless of the number of icons displayed. This will prevent the shifting of the org name as shown on the screenshot you shared on this PR. and improves user experience.

**Review by Priscilla-AL — COMMENTED** [review]
Hi Daniel, works as expected but I have two concerns
1.  The KCCA dashboard still says "Welcome to the AirQo ANALYTICS dashboard"
2. Having two logos of the same organisation next to each other looks like repetition to me.
Would it be okay with the PO or users is the organisation name changed here instead. "Welcome to the AirQo/KCCA/ETC ANALYTICS dashboard" then probably have powered by or managed by Airqo somewhere in the footer. 

Just a thought

**Review by Baalmart — COMMENTED** [review]
Thanks @danielogen 
Somehow unrelated to the PR purpose but getting a runtime error when I checkout the **Device Management** page. Please see screenshot.

image

**Comment by ja-odur** [comment]
> Thanks @danielogen
> Somehow unrelated to the PR purpose but getting a runtime error when I checkout the **Device Management** page. Please see screenshot.
> 
> image

Staging has a fix for this. @daniel you may need to rebase with staging.

**Comment by danielogen** [comment]
> > Thanks @danielogen
> > Somehow unrelated to the PR purpose but getting a runtime error when I checkout the **Device Management** page. Please see screenshot.
> > image
> 
> Staging has a fix for this. @daniel you may need to rebase with staging.

Yes...this has been resolved. Thanks

**Comment by danielogen** [comment]
> Thanks @danielogen
> Somehow unrelated to the PR purpose but getting a runtime error when I checkout the **Device Management** page. Please see screenshot.
> 
> image

Thanks, @Baalmart. This is has been resolved.

**Comment by danielogen** [comment]
> Hi Daniel, works as expected but I have two concerns
> 
> 1. The KCCA dashboard still says "Welcome to the AirQo ANALYTICS dashboard"
> 2. Having two logos of the same organisation next to each other looks like repetition to me.
>    Would it be okay with the PO or users is the organisation name changed here instead. "Welcome to the AirQo/KCCA/ETC ANALYTICS dashboard" then probably have powered by or managed by Airqo somewhere in the footer.
> 
> Just a thought

@Baalmart, what is your say on this (especially for the "Welcome......")?.
For the logos ( I believe `mak` and `airqo`), the PO wanted both to be there.

**Comment by ja-odur** [comment]
@danielogen Added a commit that puts the logos in a fixed container. Please review the changes

Screenshot 2020-10-16 at 00 27 34

Screenshot 2020-10-16 at 00 27 51

**Comment by danielogen** [comment]
> @danielogen Added a commit that puts the logos in a fixed container. Please review the changes
> 
> Screenshot 2020-10-16 at 00 27 34
> 
> Screenshot 2020-10-16 at 00 27 51

Tested and looks good to me. Thanks @ja-odur

**Review by Baalmart — APPROVED** [review]
brilliant

**Pull request merged**
