### PR TITLE
Mob 94 addressing user feedback

### PR DESCRIPTION
**Pull request by NoahNsimbe**
#### Summary of Changes (What does this PR do?)

- [x] Reimplemented map, home and search pages using bloc pattern and state management.
- [x] Created separate packages for the AirQo api.
- [x] Expanded the search scope to include Ghana, Nigeria,  Ethiopia and Kenya
- [x] Fixed bug on enabling and disabling location and notifications.
- [x] Adds Error Dialog on logout failure

#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [x] I consider this code done
- [x] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* [Android Test APK](https://play.google.com/apps/test/RQpWIE6dKj0/ahABH4UwYbaA2Q-NMaK5D8tOLeFZ7nPb56jRxSV86Z9Cv2Ie_oOJaAzHzEm58X22rDNCGdAvbGA9ygzu7cMCJSIjBH)

#### What are the relevant tickets?
- [ticket_id]()

#### Screenshots (optional)

### CODE REVIEW

**Review by Baalmart — COMMENTED** [review]
Hi @NoahNsimbe , thanks a lot for this.

It might be helpful for you to add some guiding review comments since the number of changed files is huge.

Thanks!

**Comment by BenjaminSsempala** [comment]
@NoahNsimbe , I ran the app, seems to be working well.
I noticed the few bugs( three dots on insights, favorites page misbehaving, and 17a) I'd seen earlier are resolved.

**Review by BenjaminSsempala — APPROVED** [review]
LGTM.

**Comment by NoahNsimbe** [comment]
> Hi @NoahNsimbe , thanks a lot for this.
> 
> It might be helpful for you to add some guiding review comments since the number of changed files is huge.
> 
> Thanks!

That's right @Baalmart . We are refactoring the entire code base to use state management as stated in the PR description. 
Below are a few resources you can make the most of to understand state management in flutter and the motivation of this PR after which the changed files shall make more meaning.

- [ ] https://docs.flutter.dev/development/data-and-backend/state-mgmt/options
- [ ] https://medium.com/codechai/architecting-your-flutter-project-bd04e144a8f1
- [ ] https://bloclibrary.dev/#/
- [ ] https://pub.dev/packages/flutter_bloc

**Comment by Baalmart** [comment]
> > Hi @NoahNsimbe , thanks a lot for this.
> > It might be helpful for you to add some guiding review comments since the number of changed files is huge.
> > Thanks!
> 
> That's right @Baalmart . We are refactoring the entire code base to use state management as stated in the PR description. Below are a few resources you can make the most of to understand state management in flutter and the motivation of this PR after which the changed files shall make more meaning.
> 
> * [x]  https://docs.flutter.dev/development/data-and-backend/state-mgmt/options
> * [x]  https://medium.com/codechai/architecting-your-flutter-project-bd04e144a8f1
> * [x]  https://bloclibrary.dev/#/
> * [x]  https://pub.dev/packages/flutter_bloc

Thanks @NoahNsimbe for the clarification.

**Pull request merged**
