### PR TITLE
add python auto linter

### PR DESCRIPTION
**Pull request by 123MwanjeMike**
#### Summary of Changes (What does this PR do?)
- Adds a python precommit auto linting hook

#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [x] I consider this code done
- [x] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* Make an unformatted change to a python file 
* Attempt to commit the changes
* The changes should automatically be formatted

#### What are the relevant tickets?
- [Add style guides and linters to the codebase](https://github.com/airqo-platform/AirQo-api/issues/748)

#### Screenshots (optional)

### CODE REVIEW

**Comment by 123MwanjeMike** [comment]
This is a sister PR to [this backend PR](https://github.com/airqo-platform/AirQo-api/pull/1063)

**Review by Baalmart — APPROVED** [review]
LGTM

**Review by BenjaminSsempala — APPROVED** [review]
LGTM

**Review by Mnoble-19 — APPROVED** [review]
LGTM

**Review by NoahNsimbe — APPROVED** [review]
LGTM

**Pull request merged**
