### PR TITLE
move-to-production

### PR DESCRIPTION
**Pull request by 123MwanjeMike**
- [x] #911 
- [x] #862 
- [x] #917 
- [x] #927
- [x] https://github.com/airqo-platform/AirQo-frontend/pull/928
- [x] https://github.com/airqo-platform/AirQo-frontend/pull/926
- [x] https://github.com/airqo-platform/AirQo-frontend/pull/922
- [x] https://github.com/airqo-platform/AirQo-frontend/pull/924
- [x] https://github.com/airqo-platform/AirQo-frontend/pull/923
- [x] https://github.com/airqo-platform/AirQo-frontend/pull/919
- [x] https://github.com/airqo-platform/AirQo-frontend/pull/915

### CODE REVIEW

**Review by NoahNsimbe — CHANGES_REQUESTED** [review]
Hi @123MwanjeMike. Staging for the mobile app  is not ready to be merged to master.

**Comment by 123MwanjeMike** [comment]
> Hi @123MwanjeMike. Staging for the mobile app is not ready to be merged to master.

No worries @NoahNsimbe 
Remember that we are using this PR to deploy ready apps to production and that we are using releases to show the stable versions of the codebase.
Ideally, the mobile app will not have to block ready apps from progressing cc @Baalmart

**Comment by NoahNsimbe** [comment]
> > Hi @123MwanjeMike. Staging for the mobile app is not ready to be merged to master.
> 
> No worries @NoahNsimbe Remember that we are using this PR to deploy ready apps to production and that we are using releases to show the stable versions of the codebase. Ideally, the mobile app will not have to block ready apps from progressing cc @Baalmart

Thanks @123MwanjeMike. Currently we are creating a new version using the master branch (stable codebase). Will merging this PR alter the code on the master branch? @123MwanjeMike

**Comment by 123MwanjeMike** [comment]
> Thanks @123MwanjeMike. We are creating a new version (in review) using the master branch (stable codebase). Will merging this PR alter the code on the master branch? @123MwanjeMike

That makes sense @NoahNsimbe. What you need to do now is create a new release from the current state of master. You can use that release to create a new version at any time in the future without having to block other product changes from progressing. When the PR is merge to master, it'll not affect the state of the release you made.

**Review by NoahNsimbe — APPROVED** [review]
LGTM...Thanks @123MwanjeMike

**Pull request merged**
