### PR TITLE
remove .idea folder from git cache

### LINKED ISSUE #912: Remove .idea mobile folder from git and GitHub
**Is your feature request related to a problem? Please describe.**
The[ .idea folder](https://github.com/airqo-platform/AirQo-frontend/tree/staging/mobile/.idea) in the [mobile app folder](https://github.com/airqo-platform/AirQo-frontend/tree/staging/mobile) is still tracked by git yet the [.gitignore file](https://github.com/airqo-platform/AirQo-frontend/blob/b9ea64a3ae55a75904e225db31dc19010985888d/mobile/.gitignore#L16) was setup to ignore it.

**Describe the solution you'd like**
Any future modifications to the [.idea folder](https://github.com/airqo-platform/AirQo-frontend/tree/staging/mobile/.idea) on a developer's machine should not be tracked by git.

**Describe alternatives you've considered**
None

**Additional context**
Related PRs
- https://github.com/airqo-platform/AirQo-frontend/pull/911
- The solution simply involves deleting the [.idea](https://github.com/airqo-platform/AirQo-frontend/tree/staging/.idea) at the repo root and [.idea](https://github.com/airqo-platform/AirQo-frontend/tree/staging/mobile/.idea) in the mobile app folder

### PR DESCRIPTION
**Pull request by HassanBahati**
#### Summary of Changes (What does this PR do?)
- This pr closes #912 and removes .idea directory from project root and under the mobile directory

#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [x] I consider this code done
- [x] I've tested this locally
- [x] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* The `.idea` folder shouldn't be appearing under files pushed to github
* 
#### What are the relevant tickets?
- [#912](#912)

#### Screenshots (optional)
Screenshot from 2022-11-08 19-15-02
Screenshot from 2022-11-08 19-15-53

### CODE REVIEW

**Review by 123MwanjeMike — APPROVED** [review]
Thanks @HassanBahati 
LGTM

**Comment by HassanBahati** [comment]
> Thanks @HassanBahati LGTM

It is a pleasure @123MwanjeMike

**Review by BenjaminSsempala — APPROVED** [review]
LGTM

**Review by NoahNsimbe — APPROVED** [review]
LGTM Thanks @HassanBahati

**Review by Mnoble-19 — APPROVED** [review]

**Pull request merged**
