### PR TITLE
[NetManager] Fix device overview page

### PR DESCRIPTION
**Pull request by ja-odur**
#### Summary of Changes (What does this PR do?)
- Fix device overview page

#### Is this change ready to hit production in its current state?
- [ ] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [ ] I consider this code done
- [ ] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* Install requirements `npm install`
* Start the application `npm run stage-mac` (on macOS) or `npm run stage-pc` (Windows platform)
* Navigate to the device overview page. all the graphs and tables should load

#### What are the relevant tickets?
- [ticket_id]()

#### Screenshots (optional)

### CODE REVIEW

**Review by lilly-muyama — APPROVED** [review]
Looks very good. I think it would be better to have an even number of cards though so maybe we add or delete one.

**Review by sserurich — APPROVED** [review]
this looks good.

**Comment by danielogen** [comment]
Hi @ja-odur, is there a way we can adjust the alignment below i.e Device Uptime and Maintenance History cards to be at the same level?
Screenshot 2020-11-25 at 17 07 43

**Review by danielogen — APPROVED** [review]
Looks very nice

**Comment by ja-odur** [comment]
> Hi @ja-odur, is there a way we can adjust the alignment below i.e Device Uptime and Maintenance History cards to be at the same level?
> Screenshot 2020-11-25 at 17 07 43

Thank you. @lilly-muyama had mentioned this earlier. Let me fix it.

**Review by Priscilla-AL — APPROVED** [review]
looks good

**Comment by ja-odur** [comment]
> > Hi @ja-odur, is there a way we can adjust the alignment below i.e Device Uptime and Maintenance History cards to be at the same level?
> > Screenshot 2020-11-25 at 17 07 43
> 
> Thank you. @lilly-muyama had mentioned this earlier. Let me fix it.

Fixed @danielogen

**Pull request merged**
