### PR TITLE
Refactor update password via an email token

### PR DESCRIPTION
**Pull request by Baalmart**
#### Summary of Changes (What does this PR do?)

- [ ] Introduces multi-tenancy to the react route for resetting the password. This was causing a runtime error.
- [ ] Refactors the implementation to reduce complexity of using multiple endpoints

#### Is this change ready to hit production in its current state?
- [ ] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [ ] I consider this code done
- [ ] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
```
cd AirQo-frontend/netmanager
npm install
```
`npm run dev-mac` for Linux and `npm run dev-pc` for Windows

Please remember to run the corresponding [backend PR](https://github.com/airqo-platform/AirQo-api/pull/263) within a separate shell tab.

-  Go to the password forgot page and send a reset link
- Afterwards, click on the sent link shared in email to proceed with the reset process.

#### What are the relevant tickets?
N/A

#### Screenshots (optional)

### CODE REVIEW

**Comment by DennisReddyhoff** [comment]
Getting an error on Windows:

> Failed to compile.
> 
> ./src/views/components/DataDisplay/DeviceView/DeviceView.js
> Module not found: Can't resolve 'assets/css/device-view.css' in 'C:\Projects\AirQo\src\AirQo-frontend\netmanager\src\views\components\DataDisplay\DeviceView'
> Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'

See this post about possible solution:
https://www.reddit.com/r/node/comments/ikgt1x/error_from_chokidar_c_error_ebusy_resource_busy/g5gsj0m?utm_source=share&utm_medium=web2x&context=3

Seems to be a Windows issue with backslashes?

**Comment by Baalmart** [comment]
Thanks for the review @DennisReddyhoff ...let me also investigate.... cc: @ja-odur @danielogen 

> Getting an error on Windows:
> 
> > Failed to compile.
> > ./src/views/components/DataDisplay/DeviceView/DeviceView.js
> > Module not found: Can't resolve 'assets/css/device-view.css' in 'C:\Projects\AirQo\src\AirQo-frontend\netmanager\src\views\components\DataDisplay\DeviceView'
> > Error from chokidar (C:): Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'
> 
> See this post about possible solution:
> https://www.reddit.com/r/node/comments/ikgt1x/error_from_chokidar_c_error_ebusy_resource_busy/g5gsj0m?utm_source=share&utm_medium=web2x&context=3
> 
> Seems to be a Windows issue with backslashes? Notice that in the error the path it can't resolve uses forward slashes while the path its trying to resolve from is backslashes

**Comment by DennisReddyhoff** [comment]
image
image

This is the error when running npm run dev-pc

**Comment by danielogen** [comment]
> image
> image
> 
> This is the error when running npm run dev-pc

This is often related to missing `.env` file. cc @Baalmart

**Review by ja-odur — APPROVED** [review]
LGTM

**Review by danielogen — APPROVED** [review]
Looking good. It works, awesome stuff!!

**Pull request merged**
