### PR TITLE
[NetManager] Mobile Responsiveness part 3

### PR DESCRIPTION
**Pull request by ja-odur**
#### Summary of Changes (What does this PR do?)
- Mobile responsiveness for login, forgot-password, request-access, reset-password pages

#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [x] I consider this code done
- [ ] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* Fetch this branch locally
* Install requirements using `npm install`
* Start Application using `npm run stage-mac` (MacOs) or `npm run stage-pc` (Windows PC)
* Navigate to the pages stated above, they should be responsive.

#### What are the relevant tickets?
- [PLAT-501](https://airqoteam.atlassian.net/browse/PLAT-501)

#### Screenshots (optional)

### CODE REVIEW

**Review by NoahNsimbe — COMMENTED** [review]
Great work @ja-odur. Just a few checks, I am using a browser, not sure how it will look on a real mobile device.........

1. The "Support and Feedback" button covers some buttons, find screenshots attached....
2. The dropdown doesn't look very responsive, hope it will be responsive on a real device
login_error
request_access_one

**Review by lilly-muyama — APPROVED** [review]
LGTM. Maybe in future, on the `request access` page, the "Outline in detailed nature your interest in Air Quality" can be shortened as before typing, it exceeds the boundaries of text area.

**Comment by ja-odur** [comment]
> Great work @ja-odur. Just a few checks, I am using a browser, not sure how it will look on a real mobile device.........
> 
> 1. The "Support and Feedback" button covers some buttons, find screenshots attached....
> 2. The dropdown doesn't look very responsive, hope it will be responsive on a real device
>    login_error
>    request_access_one

Thanks @NoahNsimbe , This [PR](https://github.com/airqo-platform/AirQo-frontend/pull/229) has the implementation of hiding the feedback button (unfortunately, Atlassian does not provide a responsive form of the button). I am not sure what you meant by the `dropdown` (I dont see it on the screenshot)  but will assume it's the last the multiline field on the form which is fixed.

**Comment by ja-odur** [comment]
> LGTM. Maybe in future, on the `request access` page, the "Outline in detailed nature your interest in Air Quality" can be shortened as before typing, it exceeds the boundaries of text area.

@lilly-muyama this has been fixed

**Review by NoahNsimbe — APPROVED** [review]
LGTM

**Review by danielogen — APPROVED** [review]
LGTM

**Pull request merged**
