### PR TITLE
Locate Service Maintenance

### PR DESCRIPTION
**Pull request by danielogen**
#### Summary of Changes (What does this PR do?)
- Align locate microservice routes and request body to the new [API documentation](https://app.gitbook.com/o/-MCogOVGQqjUharJKchL/s/-MKqyQkcfs54GYi-q96G/locate) 

#### Is this change ready to hit production in its current state?
- [X] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [X] I consider this code done
- [X] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
- Fetch and checkout to this branch locally
- Install requirements` npm install`
- Start `netmanager` application `npm run stage-mac` (macOS) or `npm run stage-pc`(windows Platform)
- Test out the locate feature on the platform

NB: Make sure the locate service backend is running: https://github.com/airqo-platform/AirQo-api/pull/165

#### What are the relevant tickets?
- N/A

#### Screenshots (optional)

### CODE REVIEW

**Review by 123MwanjeMike — APPROVED** [review]
LGTM

**Review by ja-odur — APPROVED** [review]
LGTM

**Comment by 123MwanjeMike** [comment]
> @123MwanjeMike , I hope the ENVS for this merged service are all up to date in the cluster? cc: @danielogen

Are there any changed environment variables for this @danielogen?

**Comment by danielogen** [comment]
Hi @123MwanjeMike , I don't remember changing the env variables

**Pull request merged**
