### PR TITLE
[WEBSITE] Homepage French translation

### PR DESCRIPTION
**Pull request by FaithDaka**
#### Summary of Changes (What does this PR do?)

- Includes `manual` translation of all sections of the homepage to french.
- Integration of `i18next` library for internationalisation.
- Translation toggle functionality added to topbar nav
- Updated the airQloud count UI to prompt clicking

#### Status of maturity (all need to be checked before merging):

- [x] I've tested this locally
- [x] I consider this code done
- [x] This change ready to hit production in its current state
- [x] The title of the PR states what changed and the related issues number (used for the release note).
- [x] I've included issue number in the "Closes #ISSUE-NUMBER" part of the "[What are the relevant tickets?](#what-are-the-relevant-tickets)" section to [link the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [ ] I've updated corresponding documentation for the changes in this PR.
- [ ] I have written unit and/or e2e tests for my change(s).

#### How should this be manually tested?

- In deploy preview, toggle translation from English to French. Translation only available for homepage

#### What are the relevant tickets?

- [WEB-410]

#### Screenshots 
image

image

image

[WEB-410]: https://airqoteam.atlassian.net/browse/WEB-410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by Baalmart** [comment]
Hi @FaithDaka , thanks for this. 
This PR has a few merge conflicts that need to be resolved.

**Review by Baalmart — COMMENTED** [review]
Thanks @FaithDaka  for this, much appreciated!

I have a couple of comments for your review, they are embedded in the **attached screenshots**. Thanks again!
Screenshot 2023-10-13 at 12 10 30
Screenshot 2023-10-13 at 12 12 13
Screenshot 2023-10-13 at 12 13 15

**Review by Baalmart — COMMENTED** [review]
Hi @FaithDaka ,
Additionally, we could also add some unit tests since this is a new functionality?
Thanks!

**Comment by FaithDaka** [comment]
@Baalmart This PR is for `Homepage` translation as titled. Translation will be a gradual process and the Q4 Key result is 40% translation as we require proofreading as well.

**Comment by Baalmart** [comment]
> @Baalmart This PR is for `Homepage` translation as titled. Translation will be a gradual process and the Q4 Key result is 40% translation as we require proofreading as well.

Thanks @FaithDaka , missed the detail in the title! Apologies.
Please look into the merge conflicts accordingly.

**Comment by FaithDaka** [comment]
@Baalmart Can we have this PR merged after the current staging has been deployed to production? The CLEAN-Air website needs to be displayed

**Comment by Baalmart** [comment]
> @Baalmart Can we have this PR merged after the current staging has been deployed to production? The CLEAN-Air website needs to be displayed

Alright @FaithDaka .....sounds good to me.
I will be waiting for you to share a QA "report" of how things are looking like in the current STAGING. 
How are things looking like?

**Comment by Baalmart** [comment]
On the same recent note you have shared, I have just made the PR a `work in progress` and converted it to `DRAFT` mode. @FaithDaka

**Comment by FaithDaka** [comment]
@Baalmart I don't think the drafting is necessary (since that usually leads to PRs being forgotten). It just needs to be merged after a recent move to production. I hope that is not a problem

**Comment by FaithDaka** [comment]
Ready for re-review @Baalmart

**Review by Baalmart — APPROVED** [review]
thanks @FaithDaka

**Pull request merged**
