### PR TITLE
Sets and updates device deployment status

### PR DESCRIPTION
**Pull request by Codebmk**
#### Summary of Changes (What does this PR do?)
- Uses the` status` field to display deployment status instead of using `isActive`
- Removed Lat and Long coordinates field in Device Deployment Section

#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [ ] I consider this code done
- [ ] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* git pull origin staging
* git checkout ft-device-deploy-statuses
* npm run stage

#### What are the relevant tickets?
- [AN-105](https://airqoteam.atlassian.net/browse/AN-105)

device registry 2
device registry 3

device registry

### CODE REVIEW

**Review by Baalmart — CHANGES_REQUESTED** [review]
Thanks @Codebmk for the amazing work here!
In addition to other comments I have left behind, please review the details in the attached screenshot too.
Screenshot 2022-09-20 at 18 59 27

**Review by 123MwanjeMike — APPROVED** [review]
Thanks @Codebmk
LGTM

**Review by Baalmart — APPROVED** [review]
LGTM

**Review by NoahNsimbe — APPROVED** [review]
LGTM

**Pull request merged**
