### PR TITLE
Ft device status summary frontend

### PR DESCRIPTION
**Pull request by danielogen**
What does this PR do?
Display device monitoring card Infos (Number of devices, Devices on solar, Devices on main power and number of devices due for maintenance)
Which JIRA card(s)?
The JIRA card for this PR is [here](https://airqoteam.atlassian.net/browse/NET-10)
How do I test out this PR?
Git clone this repo `cd AirQo-fronted/locate`, then run `npm install` to get all the necessary dependencies. After, run `npm run local` to view the changes. Remember to have the backend service running as well. Check the [API](https://docs.google.com/spreadsheets/d/1-NGTDBtTcIi8Fg2UYSWjcK6geKrZdopz5kxRFsCEMPs/edit#gid=1063367751) documentation for details.
Which endpoints should be /are ready for testing?
There are no endpoints for testing this PR.

### CODE REVIEW

**Comment by danielogen** [comment]
Expected output
Screenshot 2020-06-07 at 17 47 00

**Comment by danielogen** [comment]
> @danielogen , looks like we have some merge conflicts.
> Could we update this PR after merging with our latest master branch?

Hi @Baalmart: merge conflicts resolved accordingly. Let me hope all is good now. Thank you!

**Comment by danielogen** [comment]
Hi Ninjas: Kindly review and let me know any modification required. Thank you all.
Screenshot 2020-06-19 at 16 46 31

**Comment by danielogen** [comment]
> I'm wondering about some of the files changed like locateForm and locateSave which are not used in Locate anymore. Also Main.js from analytics seems to have some lines that should be removed but it shouldn't be part of this PR anyway.

Not sure how this happened but I think it could to related to `git merge master` or working with so many branches at the same them. Let me create another PR.

**Comment by danielogen** [comment]
Hi **Reviewers**, this PR is now obsolete. Please refer to this https://github.com/airqo-platform/AirQo-frontend/pull/63 PR to review suggested corrections. @lilly-muyama , @Priscilla-AL @Baalmart @sserurich. Thank you!

**Comment by lilly-muyama** [comment]
@danielogen this PR can be deleted to stop confusion since there's another PR here the issues raised here are fixed

**Pull request closed without merging**
