### PR TITLE
[NetManager] Set location defaults on chart forms

### PR DESCRIPTION
**Pull request by ja-odur**
#### Summary of Changes (What does this PR do?)
- Move locationFilterOptions to store
- Set defaults on chart forms

#### Is this change ready to hit production in its current state?
- [ ] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [ ] I consider this code done
- [ ] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

Good to have (up to reviewer's discretion):
- [ ] I've tested this on staging
- [ ] Unit test coverage of changes

#### How should this be manually tested?
* Pull and checkout to this [branch](ft-set-location-defaults-plat-61) locally
* Install node requirements `npm install`
* Start the application `npm run prod-mac` (on mac) or `npm run prod-pc` (on windows platform)
* On the dashboard, ensure the locations dropdown shows suggestions
* On clicking `Customise chart` on the chart dropdown, all the form fields must be pre-filled.
#### What are the relevant tickets?
- [PLAT-61](https://airqoteam.atlassian.net/browse/PLAT-61)

#### Screenshots (optional)

### CODE REVIEW

**Review by lilly-muyama — CHANGES_REQUESTED** [review]
Please add  a command for Windows users

**Comment by ja-odur** [comment]
> Please add a command for Windows users

This has been fixed.

**Review by lilly-muyama — APPROVED** [review]
Works as expected

**Review by danielogen — APPROVED** [review]
Great! works as expected

**Review by Baalmart — COMMENTED** [review]
All works as expected. @ja-odur 
Just a few questions:
-  Looks like the sign-out no longer functions as expected.
-  What backend PR is pending for the second item in the PR description?

**Comment by ja-odur** [comment]
> All works as expected. @ja-odur
> Just a few questions:
> 
> * Looks like the sign-out no longer functions as expected.
> * What backend PR is pending for the second item in the PR description?

The BEND PR has been sorted. will update the description. looking into the logout issue.

**Review by Baalmart — CHANGES_REQUESTED** [review]
Actually, please navigate to all the pages/functionalities of the app. 
Looks like something is off. Could be the state or the URL configs...not sure.
@ja-odur

**Comment by ja-odur** [comment]
> Actually, please navigate to all the pages/functionalities of the app.
> Looks like something is off. Could be the state or the URL configs...not sure.
> @ja-odur

This has been addressed @Baalmart. I had accidentally made the useEffect callback async crashing the entire react lib on loading dashboards.

**Comment by Baalmart** [comment]
> > Actually, please navigate to all the pages/functionalities of the app.
> > Looks like something is off. Could be the state or the URL configs...not sure.
> > @ja-odur
> 
> This has been addressed @Baalmart. I had accidentally made the useEffect callback async crashing the entire react lib on loading dashboards.

Cool, thanks. All looks and works as expected now.

**Review by Baalmart — APPROVED** [review]
LGTM now, awesome.

**Pull request merged**
