### PR TITLE
Update old versions of GitHub actions

### LINKED ISSUE #990: Update old versions of GitHub actions
**What were you trying to achieve?**
- Run a Github workflow

**What are the expected results?**
- All actions to run without any errors/warnings

**What are the received results?**
- All outdated versions of GitHub apps threw the warnings below
  image
  image

**What are the steps to reproduce the issue?**
- Re run any previously run GitHub action.
- You should see the warnings after the run
- A sample run with the warning is [here](https://github.com/airqo-platform/AirQo-frontend/actions/runs/3574575786)

**Additional context**
- This is because the currently used versions of the GitHub actions are using [Node12 which is being phased out by GitHub](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
- The GitHub actions to update include
  - [ ] [docker/login-action](https://github.com/docker/login-action) https://github.com/airqo-platform/AirQo-frontend/blob/12bb9a6ec998f0c08b3945b661bfc13dc1f98b16/.github/workflows/deploy-frontends-to-staging.yml#L121
  - [ ] [azure/k8s-set-context](https://github.com/Azure/k8s-set-context) https://github.com/airqo-platform/AirQo-frontend/blob/12bb9a6ec998f0c08b3945b661bfc13dc1f98b16/.github/workflows/deploy-frontends-to-staging.yml#L147
- The ideal solution updates these versions in [all the workflows](https://github.com/airqo-platform/AirQo-frontend/tree/staging/.github/workflows).

### PR DESCRIPTION
**Pull request by HassanBahati**
#### Summary of Changes (What does this PR do?)
Updates old versions of GitHub actions to newer versions.

PS: all updates are compatible with [actions/checkout@v3](https://github.com/actions/checkout)

Actions References
[google github action - auth](https://github.com/google-github-actions/auth)
[k8s-set-context](https://github.com/Azure/k8s-set-context)
[login-action](https://github.com/docker/login-action)
[setup-gcloud](https://github.com/google-github-actions/setup-gcloud)
[setup-node](https://github.com/actions/setup-node)
[create-json](https://github.com/jsdaniell/create-json)
[change-string-case-action](https://github.com/ASzc/change-string-case-action)
[dart-code-metrics-action](https://github.com/dart-code-checker/dart-code-metrics-action)
[cypress-github-action](https://github.com/cypress-io/github-action)

#### Status of maturity (all need to be checked before merging):

- [x] I've tested this locally
- [x] I consider this code done
- [x] This change ready to hit production in its current state
- [x] The title of the PR states what changed and the related issues number (used for the release note).
- [x] I've included issue number in the "Closes #ISSUE-NUMBER" part of the "[What are the relevant tickets?](#what-are-the-relevant-tickets)" section to [link the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [x] I've updated corresponding documentation for the changes in this PR.
- [ ] I have written unit and/or e2e tests for my change(s).

#### How should this be manually tested?

- Please include the steps to be done inorder to setup and test this PR.
Run a Github workflow

#### What are the relevant tickets?
Closes #990

### CODE REVIEW

**Comment by HassanBahati** [comment]
cc: @123MwanjeMike

**Review by 123MwanjeMike — APPROVED** [review]
Thanks @HassanBahati 
LGTM

**Review by Baalmart — APPROVED** [review]
This is good! Thanks @HassanBahati !

**Review by Mnoble-19 — APPROVED** [review]
LGTM!

**Pull request merged**
