### PR TITLE
[website] refactor & merge all source code

### PR DESCRIPTION
**Pull request by danielogen**
#### Summary of Changes (What does this PR do?)
- The PR introduces environment separation (development, staging and production) to the website. Secret keys are managed through a common [.env](https://drive.google.com/drive/u/1/folders/16-xmeo0yCbIZQsQe5wapwOkT_HK6UHld) file and no longer exposed.
- It also fixes the link to the google play store.
- Update codebase with missing files
- General refactoring

#### Is this change ready to hit production in its current state?
- [x] Yes
- [x] No

#### Status of maturity (all need to be checked before merging):

- [x] I consider this code done
- [x] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* Please include the steps to be done in order to set up and test this PR.
The steps are available in the `README.md` file. An update db for development & testing is available [here](https://drive.google.com/drive/u/1/folders/16-xmeo0yCbIZQsQe5wapwOkT_HK6UHld)

#### What are the relevant tickets?
- [PLAT-556]
- [PLAT-583]
- [PLAT-584]
- [PLAT-588]

[PLAT-556]: https://airqoteam.atlassian.net/browse/PLAT-556

### CODE REVIEW

**Review by Baalmart — COMMENTED** [review]
Hi @danielogen 
Awesome work! However, I am not able to get things working, could be missing something.
Please see attached screenshots and advise accordingly.

image
image
image

**Comment by danielogen** [comment]
> Hi @danielogen
> Awesome work! However, I am not able to get things working, could be missing something.
> Please see attached screenshots and advise accordingly.
> 
> image
> image
> image

Thanks @Baalmart, looks like you are missing a table (NOT sure why). Let me share that table with you on slack. You can import to the rest of the db. To login in to the DB locally, use the following credentials: `username: root, password: root, database: airqo_airqo`.
All is working well on my end though.

**Comment by Baalmart** [comment]
Hi @danielogen 
Still unable to test out, I guess I might need another DB dump. Using these credentials presents me with an empty DB and attempts to import the dump from UI brings the attached screenshot errors.......
Screenshot 2021-06-18 at 06 04 04


> > Hi @danielogen
> > Awesome work! However, I am not able to get things working, could be missing something.
> > Please see attached screenshots and advise accordingly.
> > image
> > image
> > image
> 
> Thanks @Baalmart, looks like you are missing a table (NOT sure why). Let me share that table with you on slack. You can import to the rest of the db. To login in to the DB locally, use the following credentials: `username: root, password: root, database: airqo_airqo`.
> All is working well on my end though.

**Comment by danielogen** [comment]
> Hi @danielogen 
> 
> Still unable to test out, I guess I might need another DB dump. Using these credentials presents me with an empty DB and attempts to import the dump from UI brings the attached screenshot errors.......
> 
> Screenshot 2021-06-18 at 06 04 04
> 
> 
> 
> 
> 
> > > Hi @danielogen
> 
> > > Awesome work! However, I am not able to get things working, could be missing something.
> 
> > > Please see attached screenshots and advise accordingly.
> 
> > > image
> 
> > > image
> 
> > > image
> 
> > 
> 
> > Thanks @Baalmart, looks like you are missing a table (NOT sure why). Let me share that table with you on slack. You can import to the rest of the db. To login in to the DB locally, use the following credentials: `username: root, password: root, database: airqo_airqo`.
> 
> > All is working well on my end though.
> 
> 
> 
> 
> 
> 
> 
> 

Thanks for the review @Baalmart. There is a link to a updated db dumb in the PR description...you could check it out.

**Comment by Baalmart** [comment]
> > Hi @danielogen
> > Still unable to test out, I guess I might need another DB dump. Using these credentials presents me with an empty DB and attempts to import the dump from UI brings the attached screenshot errors.......
> > Screenshot 2021-06-18 at 06 04 04
> > > > Hi @danielogen
> > 
> > 
> > > > Awesome work! However, I am not able to get things working, could be missing something.
> > 
> > 
> > > > Please see attached screenshots and advise accordingly.
> > 
> > 
> > > > image
> > 
> > 
> > > > image
> > 
> > 
> > > > image
> > 
> > 
> > > 
> > 
> > 
> > > Thanks @Baalmart, looks like you are missing a table (NOT sure why). Let me share that table with you on slack. You can import to the rest of the db. To login in to the DB locally, use the following credentials: `username: root, password: root, database: airqo_airqo`.
> > 
> > 
> > > All is working well on my end though.
> 
> Thanks for the review @Baalmart. There is a link to a updated db dumb in the PR description...you could check it out.

Alright, let me check it out asap... @danielogen

**Review by NoahNsimbe — APPROVED** [review]
LGTM

**Review by Baalmart — APPROVED** [review]
All looks and works well. Very primising! I hope that the plans to move some of the implememtations to the microservices will refdiuce the filse size

**Pull request merged**
