### PR TITLE
[Netmanager] Add country field to request data access form

### PR DESCRIPTION
**Pull request by Codebmk**
#### Summary of Changes (What does this PR do?)

- [x] added country dropdown in the register form

#### Status of maturity (all need to be checked before merging):

- [ ] I've tested this locally
- [ ] I consider this code done
- [ ] This change ready to hit production in its current state
- [ ] The title of the PR states what changed and the related issues number (used for the release note).
- [ ] I've included issue number in the "Closes #ISSUE-NUMBER" part of the "[What are the relevant tickets?](#what-are-the-relevant-tickets)" section to [link the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [ ] I've updated corresponding documentation for the changes in this PR.
- [ ] I have written unit and/or e2e tests for my change(s).

#### How should this be manually tested?

- Please include the steps to be done inorder to setup and test this PR.

#### What are the relevant tickets?

- Closes #<enter issue number here>
- [Jira_card_number]() (If exists)

### CODE REVIEW

**Review by NoahNsimbe — COMMENTED** [review]
Thanks @Codebmk 
Where can I found the country before approving??
Screenshot 2023-02-07 at 15 19 36

**Comment by Codebmk** [comment]
> Thanks @Codebmk Where can I found the country before approving?? Screenshot 2023-02-07 at 15 19 36

Considered that but didnt think it was needed there. Let me add it for future purposes. Thanks

**Comment by Codebmk** [comment]
@NoahNsimbe I have added the country column to the candidates and users tables
Screenshot from 2023-02-07 16-21-36

**Comment by NoahNsimbe** [comment]
> > Thanks @Codebmk Where can I found the country before approving?? Screenshot 2023-02-07 at 15 19 36
> 
> Considered that but didnt think it was needed there, the table already has quite a number of fields. Let me add it for future requests. Thanks

Is it possible to have a view more option. @Codebmk

**Review by 123MwanjeMike — COMMENTED** [review]
Hi @Codebmk 
This branch is outdated. You need to pull changes from staging for that preview to work

**Review by Baalmart — COMMENTED** [review]
Thanks @Codebmk , this looks good.
Looking forward to the deploy link working.... cc: @123MwanjeMike

**Comment by Codebmk** [comment]
@123MwanjeMike the branch is up to date...

**Comment by Baalmart** [comment]
Also @Codebmk , for any future PRs, Could we explore ways of ensuring that we show more information in our list tables without adding more columns?

**Options:**

1. Expandable rows: You can create expandable rows that display additional information when clicked.
2. Tooltips: You can add tooltips to cells to display additional information when the user hovers over them.
3. Modals: You can use modals to display additional information about an item in the list.
4. Row grouping: You can group related rows together and use indentation to show hierarchy.
5. Conditional rendering: You can conditionally render certain information based on user actions or other conditions.
6. Pagination: You can break up a large list into smaller chunks using pagination, allowing the user to view more information in a manageable way.
7. Filtering: You can provide filters that allow the user to search and sort the list in different ways.

**Comment by NoahNsimbe** [comment]
> Also @Codebmk , for any future PRs, Could we explore ways of ensuring that we show more information in our list tables without adding more columns?
> 
> **Options:**
> 
> 1. Expandable rows: You can create expandable rows that display additional information when clicked.
> 2. Tooltips: You can add tooltips to cells to display additional information when the user hovers over them.
> 3. Modals: You can use modals to display additional information about an item in the list.
> 4. Row grouping: You can group related rows together and use indentation to show hierarchy.
> 5. Conditional rendering: You can conditionally render certain information based on user actions or other conditions.
> 6. Pagination: You can break up a large list into smaller chunks using pagination, allowing the user to view more information in a manageable way.
> 7. Filtering: You can provide filters that allow the user to search and sort the list in different ways.

col=

> @NoahNsimbe You mean view more columns? The current library being used for that table doesn't support it. If you want more fields, you can make the table scrollable just like we are currently doing.

Cool. No worries @Codebmk

**Review by NoahNsimbe — APPROVED** [review]
LGTM

**Review by Baalmart — APPROVED** [review]
LGTM

**Pull request merged**
