### PR TITLE
Modification to the FOR YOU section 

### PR DESCRIPTION
**Pull request by katendejericho5**
#### Summary of Changes (What does this PR do?)

- This PR adds Filters for KYA and Quiz in the KnowYourAirView widget. 

#### Status of maturity (all need to be checked before merging):

- [x] I've tested this locally
- [x] I consider this code done
- [ ] This change ready to hit production in its current state
- [ ] The title of the PR states what changed and the related issues number (used for the release note).
- [ ] I've included issue number in the "Closes #ISSUE-NUMBER" part of the "[What are the relevant tickets?](#what-are-the-relevant-tickets)" section to [link the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [ ] I've updated corresponding documentation for the changes in this PR.
- [ ] I have written unit and/or e2e tests for my change(s).

#### How should this be manually tested?

-    https://www.figma.com/file/agN9GOkAbhXfGDEXYCKwBu/Mobile-App?type=design&node-id=7193%3A41108&mode=design&t=OEn591JTP4jvoMdU-1   Confirm the designs 

#### What are the relevant tickets?

- Closes #<enter issue number here>
- [Jira_card_number]() (If exists)

### CODE REVIEW

**Comment by katendejericho5** [comment]
@2phonebabykeem

**Comment by katendejericho5** [comment]
@jordanopos  @Baalmart @2phonebabykeem   @BenjaminSsempala  this  PR is ready for review

**Review by Baalmart — APPROVED** [review]
Thanks @katendejericho5 , this looks good to me.

**Comment by Baalmart** [comment]
Hi @katendejericho5 the PR has merge conflicts now, please resolve them accordingly.

**Review by BenjaminSsempala — APPROVED** [review]

**Pull request merged**
