### PR TITLE
Locate feature - open/edit/save/delete previously saved planning space

### PR DESCRIPTION
**Pull request by danielogen**
1. What does this PR do?
It focuses on activities related to reusing previously saved locate planning space i.e. `open`, `edit`, `save`, `delete`. It also resolves some `styling` issues (where map controls are hidden) observed on the previously deployed version.
2. What JIRA task is related to this PR?
The link to the JIRA board task is [here](https://airqoteam.atlassian.net/browse/LOC-8).
3. How do I test out this PR?
Git clone this repo `cd AirQo-frontend/locate`. Then run `npm install` to get all the necessary dependencies. Afterwards, run `npm run local`. Also, ensure that all the backend services are running i.e `auth-service` and `ml-service`. Check out the instructions on how to run those services from `AirQo-api` repo.
4. Which endpoints should be ready for testing?
None

### CODE REVIEW

**Comment by danielogen** [comment]
> @danielogen , looks like we have some merge conflicts.
> Could we update this PR after merging with our latest master branch?

I hope its all good now!

**Comment by danielogen** [comment]
> @danielogen , looks like we have some merge conflicts.
> Could we update this PR after merging with our latest master branch?

Hi @Baalmart: Just letting you know that this was resolved.

**Comment by Baalmart** [comment]
> > @danielogen , looks like we have some merge conflicts.
> > Could we update this PR after merging with our latest master branch?
> 
> Hi @Baalmart: Just letting you know that this was resolved.

Hi, just noticing this response. Apologies for that. Could we have the latest conflicts resolve and we merge today? Thanks @danielogen

**Review by Baalmart — COMMENTED** [review]
change base to staging and address merge conflicts

**Comment by lilly-muyama** [comment]
@danielogen is this PR still valid? I think these features are already available in the deployed platform.

**Comment by danielogen** [comment]
> @danielogen is this PR still valid? I think these features are already available in the deployed platform.

True, this PR is no longer valid. @Baalmart on proceeding with deletion of this PR and brand. Thank you.

**Pull request closed without merging**
