### PR TITLE
[Website] Home page and about us page fixes

### PR DESCRIPTION
**Pull request by Codebmk**
#### Summary of Changes (What does this PR do?)
- Removed air quality reading from hero section
- Made hero section mobile responsive
- Made monitor section responsive
- Adde new images on about us page

#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [x] I consider this code done
- [ ] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* Do a git fetch, then checkout to this local branch to run

#### What are the relevant tickets?
- [WEB-203](https://airqoteam.atlassian.net/browse/WEB-203)
- [WEB-169](https://airqoteam.atlassian.net/browse/WEB-169)
- [WEB-168](https://airqoteam.atlassian.net/browse/WEB-168)

### CODE REVIEW

**Review by 123MwanjeMike — CHANGES_REQUESTED** [review]
Deploy breaking on my end
image

**Comment by Codebmk** [comment]
> Deploy breaking on my end image

Checking issue thanks

**Comment by Codebmk** [comment]
> Deploy breaking on my end image

@123MwanjeMike Could you do a git pull for this branch and see if that removes the trouble?

**Comment by 123MwanjeMike** [comment]
> > Deploy breaking on my end image
> 
> @123MwanjeMike Could you do a git pull for this branch and see if that removes the trouble?

I'm still getting the error even after pulling
image

**Comment by Codebmk** [comment]
> > > Deploy breaking on my end image
> > 
> > 
> > @123MwanjeMike Could you do a git pull for this branch and see if that removes the trouble?
> 
> I'm still getting the error even after pulling image

🥱

**Review by Baalmart — CHANGES_REQUESTED** [review]
- App runs well on my side. Thanks @Codebmk 
- A few things in the mobile responsiveness that need to be fixed. See attached screenshots. Thanks.
- Also, need to review these ongoing shared concerns of "works on one machine but fails on another.

The screenshots:
Screenshot 2022-05-17 at 17 35 34
Screenshot 2022-05-17 at 17 35 55
Screenshot 2022-05-17 at 17 36 19
Screenshot 2022-05-17 at 17 38 16
Screenshot 2022-05-17 at 17 38 50

**Comment by Codebmk** [comment]
hero
monitor

@Baalmart I have fixed them. Please re-review. Thanks.

**Review by FaithDaka — APPROVED** [review]

**Pull request merged**
