### PR TITLE
Changing insights graph pm colours

### PR DESCRIPTION
**Pull request by NoahNsimbe**
#### Summary of Changes (What does this PR do?)
- Changes pm colors for insights graph when you click on forecast bars.

#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [x] I consider this code done
- [x] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### What are the relevant tickets?
- [MOB-83](https://airqoteam.atlassian.net/browse/MOB-83)

#### Screenshots (optional)
IMG_5805A12BFCD4-1

### CODE REVIEW

**Review by Mnoble-19 — APPROVED** [review]
Tested on android device and working fine.

**Comment by NoahNsimbe** [comment]
> Just wondering about the "when you click" in the PR description. Sometimes, the forecast data (PM value) used to show even if one had not clicked. Does this mean that for that case, it will still be showing the AQI color? @NoahNsimbe

Hi @Baalmart the forecast is showed by default. 

**Note:** 
- This PR introduces changes that show the right AQI color when you tap a forecast bar. Doesn't address any other issues. 
- The forecast bars have remained with their default color (pale blue) as we discussed in the bi weekly meeting unless I got it wrong.

**Comment by Baalmart** [comment]
> > Just wondering about the "when you click" in the PR description. Sometimes, the forecast data (PM value) used to show even if one had not clicked. Does this mean that for that case, it will still be showing the AQI color? @NoahNsimbe
> 
> Hi @Baalmart the forecast is showed by default.
> 
> **Note:**
> 
> * This PR introduces changes that show the right AQI color when you tap a forecast bar. Doesn't address any other issues.
> * The forecast bars have remained with their default color (pale blue) as we discussed in the bi weekly meeting unless I got it wrong.

Thanks, I guess I missed that part too. 

- Without tapping the forecast (where forecast is shown by default), is it only the bars that remain pale blue or also the top right value reading below the toggle button? @NoahNsimbe

**Comment by NoahNsimbe** [comment]
Hi @Baalmart the difference between these images is the purpose of the PR.

**Before**
IMG_ACDD1E04681E-1



**After**

IMG_2244 (1)

**Pull request merged**
